import Foundation

/// THE EIP-8130 TRANSACTION, AND THE HASH THAT GETS SIGNED (prd §523,
/// 2026-08-29). Foundation-only BY DESIGN so a `swiftc` harness compiles it
/// WHOLE, which is the only way any of this can be checked.
///
/// ## THIS IS THE CLASS OF BUG THAT LOSES MONEY SILENTLY
///
/// A wrong field order, a wrong length prefix, a leading zero left on a
/// quantity, or the wrong type byte produces a signature that is perfectly
/// well-formed and recovers to a DIFFERENT address. The build is green, the
/// screen is right, the tap is right, and the transaction is somebody else's.
/// `SafeTransaction` (§425) has the same shape and answers it by refusing to
/// sign a hash Casberi computed alone — it asks the Safe for
/// `getTransactionHash` and declines on disagreement.
///
/// **Vibenet publishes no such counterpart**, so the proof had to come from
/// somewhere else, and it did: a REAL transaction off this chain carries its
/// decoded fields, its 65-byte `senderAuth`, and the `from` it was sent by.
/// Encoding the hash and recovering the signer against that address either
/// matches or does not, and **exactly one of sixteen candidate encodings
/// matched** (measured 2026-08-29, tx in block 0x243). That is a proof, not a
/// reading of a spec. The vector is pinned in
/// `scripts/vibenet-signer-selftest.sh` and regenerated by
/// `scripts/support/vibenet-tx-vectors.py`, the `safetx-vectors.py` shape.
///
/// ## WHAT IS PROVEN AND WHAT IS NOT
///
/// **Proven:** the type byte `0x79`, the field order, RLP throughout, the
/// nested shapes below, and that the sender hash covers the list THROUGH
/// `payer` while excluding both auth fields.
///
/// **Also proven, by a different method:** the `sender_auth` a CONFIGURED
/// ACTOR supplies — see `VibenetP256Auth` below, which was measured by asking
/// the deployed `P256Authenticator` directly rather than by reading a spec
/// that leaves the field authenticator-specific. For an EOA sender (`sender`
/// empty) it stays a raw 65-byte `r || s || v`, which is what the measured
/// transaction used.
enum VibenetTransaction {

    /// Measured off a real transaction's `type`, never the spec text, which
    /// names `AA_TX_TYPE` and does not give its value.
    static let txType: UInt8 = 0x79

    /// Lowercase, no `0x`. Local rather than shared because this file is
    /// deliberately compilable by a harness with nothing else in it.
    static func hex(_ data: some Sequence<UInt8>) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    static func data(fromHex hex: String) -> Data? {
        var s = Substring(hex)
        if s.hasPrefix("0x") || s.hasPrefix("0X") { s = s.dropFirst(2) }
        guard s.count % 2 == 0, !s.isEmpty else { return nil }
        var out = Data(capacity: s.count / 2)
        var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            guard let b = UInt8(s[i..<j], radix: 16) else { return nil }
            out.append(b)
            i = j
        }
        return out
    }

    // MARK: - RLP

    /// The two RLP shapes, and nothing else. An enum rather than `Any` so a
    /// caller cannot hand in a type this encoder would have to guess about.
    indirect enum Item {
        case bytes(Data)
        case list([Item])
    }

    /// Canonical big-endian with **no leading zeros, and zero is EMPTY**. This
    /// is the rule most easily got wrong and it changes the hash: RLP quantity
    /// encoding has exactly one representation per value, and `0x00` is not
    /// it — `validAfter: 0` must contribute `0x80` (empty string), never
    /// `0x00`. Mutation-proven.
    static func quantity(_ value: UInt64) -> Data {
        guard value != 0 else { return Data() }
        var v = value
        var out = [UInt8]()
        while v > 0 { out.insert(UInt8(v & 0xff), at: 0); v >>= 8 }
        return Data(out)
    }

    static func encode(_ item: Item) -> Data {
        switch item {
        case .bytes(let d):
            // A single byte below 0x80 is its own encoding — the one case with
            // no prefix at all.
            if d.count == 1, d[0] < 0x80 { return d }
            return header(d.count, offset: 0x80) + d
        case .list(let items):
            let body = items.reduce(into: Data()) { $0 += encode($1) }
            return header(body.count, offset: 0xc0) + body
        }
    }

    private static func header(_ length: Int, offset: UInt8) -> Data {
        if length < 56 { return Data([offset + UInt8(length)]) }
        let lenBytes = quantity(UInt64(length))
        return Data([offset + 55 + UInt8(lenBytes.count)]) + lenBytes
    }

    // MARK: - The shapes

    /// One call. `calls` is a two-level structure — an ordered array of
    /// PHASES, each an ordered array of calls — and flattening it changes the
    /// hash, which is one of the sixteen candidates the proof rejected.
    struct Call: Equatable {
        var to: Data
        var data: Data
        var item: Item { .list([.bytes(to), .bytes(data)]) }
    }

    /// One change inside a config-change entry. `AuthorizeActor` is tag `0x00`
    /// — measured, not assumed: the tag is one of the axes the sixteen-way
    /// search varied, and only `0x00` recovered the signer.
    struct Change: Equatable {
        var tag: UInt64
        var payload: Data
        var item: Item { .list([.bytes(quantity(tag)), .bytes(payload)]) }

        static func authorizeActor(_ payload: Data) -> Change {
            Change(tag: 0x00, payload: payload)
        }
    }

    /// One initial actor inside a Create: `[actorId, authenticator, scope,
    /// policyData]`. Measured against three real creations on this chain.
    struct InitialActor: Equatable {
        var actorID: Data
        var authenticator: Data
        var scope: UInt64
        var policyData: Data
        var item: Item {
            .list([.bytes(actorID), .bytes(authenticator),
                   .bytes(quantity(scope)), .bytes(policyData)])
        }
    }

    /// A CREATE entry: `rlp([0x00, userSalt, code, initialActors])`.
    ///
    /// **The account signs its OWN creation** — `sender` is the counterfactual
    /// account and `sender_auth` is its first actor's signature. Measured, not
    /// assumed: all seven creations on this chain are shaped that way and three
    /// of them are signed by a P-256 key. That is what makes "Face ID is the
    /// key" true end to end, with no ordinary wallet needed anywhere.
    struct CreateAccount: Equatable {
        var userSalt: Data
        var code: Data
        var initialActors: [InitialActor]
        var item: Item {
            .list([.bytes(quantity(0x00)), .bytes(userSalt), .bytes(code),
                   .list(initialActors.map(\.item))])
        }
    }

    /// An account-changes entry is one or the other. An enum rather than two
    /// arrays so a caller cannot accidentally emit both in an order the hash
    /// would notice.
    enum AccountChange: Equatable {
        case create(CreateAccount)
        case config(ConfigChange)
        var item: Item {
            switch self {
            case .create(let c): c.item
            case .config(let c): c.item
            }
        }
    }

    /// A config-change entry: `rlp([0x01, channel, sequence, changes, auth])`.
    /// `channel` is 0 for Local — also measured rather than assumed.
    struct ConfigChange: Equatable {
        var channel: UInt64 = 0
        var sequence: UInt64
        var changes: [Change]
        var auth: Data
        var item: Item {
            .list([.bytes(quantity(0x01)), .bytes(quantity(channel)),
                   .bytes(quantity(sequence)),
                   .list(changes.map(\.item)), .bytes(auth)])
        }
    }

    /// The fields the sender signs over. Deliberately a value type with no
    /// defaults for the money-shaped fields: a gas limit that defaults to zero
    /// is a transaction that cannot run, and one that defaults to something
    /// plausible is worse.
    struct Fields: Equatable {
        var chainID: UInt64
        /// Empty for an EOA sender. A populated sender means a configured
        /// actor, whose `sender_auth` this app cannot yet compose.
        var sender: Data = Data()
        var nonceKey: UInt64 = 0
        var nonceSequence: UInt64
        var validAfter: UInt64 = 0
        var validBefore: UInt64 = 0
        var maxPriorityFeePerGas: UInt64
        var maxFeePerGas: UInt64
        var gasLimit: UInt64
        var accountChanges: [AccountChange] = []
        /// Phases of calls. Empty is legal.
        var calls: [[Call]] = []
        var metadata: Data = Data()
        /// Empty unless somebody else is paying — this is the wire form of the
        /// Sponsorship the console offers as a feature card.
        var payer: Data = Data()
    }

    /// The list the SENDER hash covers: everything through `payer`, with both
    /// auth fields excluded. Shared with the full-transaction encoder so the
    /// two can never disagree about field order — which is exactly the drift
    /// that produces a signature over a different transaction.
    static func signingBody(_ f: Fields) -> [Item] {
        [.bytes(quantity(f.chainID)),
         .bytes(f.sender),
         .bytes(quantity(f.nonceKey)),
         .bytes(quantity(f.nonceSequence)),
         .bytes(quantity(f.validAfter)),
         .bytes(quantity(f.validBefore)),
         .bytes(quantity(f.maxPriorityFeePerGas)),
         .bytes(quantity(f.maxFeePerGas)),
         .bytes(quantity(f.gasLimit)),
         .list(f.accountChanges.map(\.item)),
         .list(f.calls.map { phase in Item.list(phase.map(\.item)) }),
         .bytes(f.metadata),
         .bytes(f.payer)]
    }

    /// THE BYTES THAT GET BROADCAST: `AA_TX_TYPE || rlp([...through payer,
    /// sender_auth, payer_auth])` — the signing body with the two auth fields
    /// appended, ready for `eth_sendRawTransaction`.
    ///
    /// **This is a WEAKER claim than `senderSigningPreimage`, and the
    /// difference matters more than it looks.** That function's field order is
    /// proven: re-encoding real transactions and recovering their signers
    /// passes 3/3, so a mistake there is impossible to miss. The two trailing
    /// fields cannot be proven that way — they are excluded from the hash by
    /// definition, so no recovery can see them, and this node refuses every
    /// raw-transaction read (403), so there is no encoded example to compare
    /// against. Their order comes from the spec alone.
    ///
    /// **That is survivable precisely because it fails LOUDLY.** A wrong
    /// signing hash produces a valid signature over the wrong transaction —
    /// silent, and somebody else's money. A wrong broadcast envelope is
    /// rejected by the node with an error, before anything happens. The first
    /// class had to be proven; the second announces itself the first time it is
    /// tried, which is the whole reason to try it on a devnet.
    static func encoded(_ f: Fields, senderAuth: Data, payerAuth: Data = Data()) -> Data {
        Data([txType]) + encode(.list(signingBody(f)
                                      + [.bytes(senderAuth), .bytes(payerAuth)]))
    }

    /// `AA_TX_TYPE || rlp([...through payer])` — the bytes that get hashed.
    /// Returned rather than hashed here so the harness can pin the PREIMAGE
    /// too: a hash fixture alone cannot say which of two encodings produced
    /// it, and the preimage length was one of the things the proof turned on.
    static func senderSigningPreimage(_ f: Fields) -> Data {
        Data([txType]) + encode(.list(signingBody(f)))
    }
}

// MARK: - The P-256 authenticator's wire format

/// HOW A P-256 KEY AUTHENTICATES, MEASURED AGAINST THE CONTRACT ITSELF
/// (prd §523, 2026-08-29).
///
/// The spec says a configured actor's `sender_auth` is
/// `authenticator (20 bytes) || data` and leaves `data` **authenticator-
/// specific**. No P-256 actor has ever been authorized on this chain, so there
/// is no transaction to copy. The format below was not read off a document and
/// not inferred from the other authenticators — it was **asked of the deployed
/// contract**.
///
/// `P256Authenticator` exposes `authenticate(bytes32,bytes)` (selector
/// `0x30ba1adf`, recovered by hashing candidate signatures against the
/// selectors in its own bytecode). That is a view call, so a software P-256
/// key can sign a hash and every candidate layout can be tried against the
/// real contract for the price of an `eth_call`. Measured:
///
///   • `r || s || x || y` (128 bytes) — **reverts**
///   • `r || s || x || y || <1 byte>` (129) — **returns a non-zero word**
///   • 130 and 160 bytes — **revert**
///
/// so the length is checked exactly and **129 is the format**. The trailing
/// byte's VALUE is ignored (0x00 through 0xff all answer identically), which
/// is why `padByte` is a zero rather than something that looks meaningful:
/// nothing here should imply a field that the contract does not read.
///
/// **The word it returns is the actor id**, and that was measured too rather
/// than assumed: the same key over two different messages returns the same
/// word, two different keys return different words, and a signature presented
/// for the wrong message returns **zero** — so a non-zero answer is a real
/// verification, not an echo. The word equals `keccak256(x || y)`, confirmed
/// independently for two keys.
///
/// **This is the join `VibenetSigner` needed**, and it is better than reading
/// `actorData` back: an account accepts this phone when it authorizes
/// `actorID(publicKey:)`. It stays a CANONICAL id rather than the only one —
/// the id is caller-supplied at authorize time (see the type doc above), so
/// another client may have registered the same key under a different word, and
/// a nil answer from a lookup still means cannot-say rather than no.
enum VibenetP256Auth {

    /// Measured: any value answers identically, so this is padding to reach the
    /// length the contract checks, and nothing more.
    static let padByte: UInt8 = 0x00

    /// The exact byte count `authenticate` accepts. 128 and 130 both revert, so
    /// this is not a minimum — it is the length.
    static let dataLength = 129

    /// `r || s || x || y || pad`. **Order is measured**: `x || y || r || s`
    /// reverts at this length, so a transposition here is not a stylistic
    /// choice, it is a signature the chain refuses.
    static func authData(r: Data, s: Data, publicKeyXY: Data) -> Data? {
        guard r.count == 32, s.count == 32, publicKeyXY.count == 64 else { return nil }
        return r + s + publicKeyXY + Data([padByte])
    }

    /// `authenticator || data` — what rides `sender_auth` for a configured
    /// actor. 149 bytes.
    static func senderAuth(authenticator: Data, r: Data, s: Data, publicKeyXY: Data) -> Data? {
        guard authenticator.count == 20,
              let data = authData(r: r, s: s, publicKeyXY: publicKeyXY) else { return nil }
        return authenticator + data
    }

    /// `keccak256(x || y)` — the id the contract itself answers with.
    ///
    /// Deliberately NOT `keccak256(0x04 || x || y)`: the uncompressed-point tag
    /// is how a public key is usually framed and it produces a different,
    /// plausible-looking word that the contract does not agree with. Measured
    /// both ways.
    static func actorID(publicKeyXY: Data) -> Data? {
        guard publicKeyXY.count == 64 else { return nil }
        return Data(Keccak256.hash([UInt8](publicKeyXY)))
    }
}

// MARK: - Where a new account will live

/// THE COUNTERFACTUAL ACCOUNT ADDRESS (prd §523, 2026-08-29).
///
/// A creation sets `sender` to the new account's address BEFORE it exists, so
/// the address is computed client-side and everything downstream depends on
/// getting it right: it is signed over, so a wrong one is not a wrong guess but
/// a signature over a different transaction.
///
/// **Two hidden layers made this resist a long search**, and both are the kind
/// that produce a plausible wrong answer rather than an obvious one:
///
/// 1. The actors are folded through **per-actor leaf hashes, then a hash of the
///    concatenated leaves** — not a flat concatenation and not their RLP.
/// 2. The CREATE2 init-code hash is **not** `keccak256(code)`. It is
///    `keccak256(DEPLOYMENT_HEADER ‖ code)`. `AccountCreated`'s second word IS
///    `keccak256(code)`, which makes it a decoy: it is right there in the event,
///    it looks like exactly the value CREATE2 wants, and it is the wrong one.
///
/// `scope` is **two bytes, big-endian** inside the leaf. Proven rather than
/// assumed: the deployed `Keystore.computeAddress` (selector `0x500fa70e`)
/// agrees with this computation byte for byte on a fresh parameter set, and a
/// one-byte encoding would disagree.
///
/// Verified three ways: all **7/7** creations on this chain reproduce; the node
/// itself accepts a derived sender (a wrong one is refused with "create address
/// does not match the sender", a right one advances to "insufficient funds");
/// and the Keystore's own view function returns the same word.
enum VibenetAddress {

    /// The 14-byte constructor that returns `code` as the deployed body.
    /// `61 <n:2> 60 0E 60 00 39 61 <n:2> 60 00 F3`.
    static func deploymentHeader(codeLength: Int) -> Data? {
        guard codeLength > 0, codeLength <= 0xffff else { return nil }
        let n = UInt16(codeLength)
        let hi = UInt8(n >> 8), lo = UInt8(n & 0xff)
        return Data([0x61, hi, lo, 0x60, 0x0E, 0x60, 0x00, 0x39, 0x61, hi, lo, 0x60, 0x00, 0xF3])
    }

    /// `keccak256(actorId ‖ authenticator ‖ scope(2, BE) ‖ policyData)`.
    static func leaf(_ a: VibenetTransaction.InitialActor) -> Data? {
        guard a.actorID.count == 32, a.authenticator.count == 20,
              a.scope <= UInt64(UInt16.max) else { return nil }
        let scope = UInt16(a.scope)
        let bytes = a.actorID + a.authenticator
            + Data([UInt8(scope >> 8), UInt8(scope & 0xff)]) + a.policyData
        return Data(Keccak256.hash([UInt8](bytes)))
    }

    /// Where the account will be.
    ///
    /// **Actors are sorted strictly ascending by `actorId`** — the commitment is
    /// order-dependent, so an unsorted list yields a different, perfectly
    /// valid-looking address that the node then refuses. Sorted here rather than
    /// demanded of the caller: a rule the caller has to remember is one that
    /// eventually is not.
    static func derive(keystore: Data,
                       userSalt: Data,
                       code: Data,
                       initialActors: [VibenetTransaction.InitialActor]) -> Data? {
        guard keystore.count == 20, userSalt.count == 32, !initialActors.isEmpty,
              let header = deploymentHeader(codeLength: code.count) else { return nil }
        var leaves = Data()
        for actor in initialActors.sorted(by: { $0.actorID.lexicographicallyPrecedes($1.actorID) }) {
            guard let l = leaf(actor) else { return nil }
            leaves += l
        }
        let commitment = Data(Keccak256.hash([UInt8](leaves)))
        let effectiveSalt = Data(Keccak256.hash([UInt8](userSalt + commitment)))
        let initCodeHash = Data(Keccak256.hash([UInt8](header + code)))
        let word = Keccak256.hash([UInt8](Data([0xff]) + keystore + effectiveSalt + initCodeHash))
        return Data(word.suffix(20))
    }
}
