import Foundation

/// THE EIP-8130 TRANSACTION, AND THE HASH THAT GETS SIGNED (prd §523,
/// 2026-08-29). Foundation-only BY DESIGN so a `swiftc` harness compiles it
/// WHOLE, which is the only way any of this can be checked.
///
/// ## THIS IS THE CLASS OF BUG THAT LOSES MONEY SILENTLY
///
/// A wrong field order, a wrong length prefix, a leading zero left on a
/// quantity, or the wrong type byte produces a signature that is perfectly
/// well-formed and recovers to a DIFFERENT address. The build is green, the
/// screen is right, the tap is right, and the transaction is somebody else's.
/// `SafeTransaction` (§425) has the same shape and answers it by refusing to
/// sign a hash Casberi computed alone — it asks the Safe for
/// `getTransactionHash` and declines on disagreement.
///
/// **Vibenet publishes no such counterpart**, so the proof had to come from
/// somewhere else, and it did: a REAL transaction off this chain carries its
/// decoded fields, its 65-byte `senderAuth`, and the `from` it was sent by.
/// Encoding the hash and recovering the signer against that address either
/// matches or does not, and **exactly one of sixteen candidate encodings
/// matched** (measured 2026-08-29, tx in block 0x243). That is a proof, not a
/// reading of a spec. The vector is pinned in
/// `scripts/vibenet-signer-selftest.sh` and regenerated by
/// `scripts/support/vibenet-tx-vectors.py`, the `safetx-vectors.py` shape.
///
/// ## WHAT IS PROVEN AND WHAT IS NOT
///
/// **Proven:** the type byte `0x79`, the field order, RLP throughout, the
/// nested shapes below, and that the sender hash covers the list THROUGH
/// `payer` while excluding both auth fields.
///
/// **Also proven, by a different method:** the `sender_auth` a CONFIGURED
/// ACTOR supplies — see `VibenetP256Auth` below, which was measured by asking
/// the deployed `P256Authenticator` directly rather than by reading a spec
/// that leaves the field authenticator-specific. For an EOA sender (`sender`
/// empty) it stays a raw 65-byte `r || s || v`, which is what the measured
/// transaction used.
enum VibenetTransaction {

    /// Measured off a real transaction's `type`, never the spec text, which
    /// names `AA_TX_TYPE` and does not give its value.
    static let txType: UInt8 = 0x79

    static func hex(_ data: some Sequence<UInt8>) -> String { RLP.hex(data) }
    static func data(fromHex hex: String) -> Data? { RLP.data(fromHex: hex) }

    // MARK: - RLP

    /// RLP moved to `RLP` the day Hegotá needed it too (prd §525). These are
    /// aliases rather than a second copy: two encoders of one format
    /// eventually disagree, and here a disagreement is a signature over a
    /// different transaction. The harness's pinned 613-byte preimage and its
    /// proven signing hash are what keep the move honest.
    typealias Item = RLP.Item

    static func quantity(_ value: UInt64) -> Data { RLP.quantity(value) }

    static func encode(_ item: Item) -> Data { RLP.encode(item) }

    // MARK: - The shapes

    /// One call. `calls` is a two-level structure — an ordered array of
    /// PHASES, each an ordered array of calls — and flattening it changes the
    /// hash, which is one of the sixteen candidates the proof rejected.
    struct Call: Equatable {
        var to: Data
        var data: Data
        var item: Item { .list([.bytes(to), .bytes(data)]) }
    }

    /// One change inside a config-change entry. `AuthorizeActor` is tag `0x00`
    /// — measured, not assumed: the tag is one of the axes the sixteen-way
    /// search varied, and only `0x00` recovered the signer.
    struct Change: Equatable {
        var tag: UInt64
        var payload: Data
        var item: Item { .list([.bytes(quantity(tag)), .bytes(payload)]) }

        static func authorizeActor(_ payload: Data) -> Change {
            Change(tag: 0x00, payload: payload)
        }

        /// Tag `0x01` — `Keystore.sol`'s `ChangeType.RevokeActor`, one past
        /// `AuthorizeActor` in the same declaration order
        /// (`VibenetAccountChanges.revokeActor`). Unlike `AuthorizeActor`
        /// this one is UNMEASURED against a real transaction (no revoke has
        /// ever landed on this chain to compare against) — read from source,
        /// not guessed, but still worth stating plainly per this file's own
        /// rule.
        static func revokeActor(_ payload: Data) -> Change {
            Change(tag: 0x01, payload: payload)
        }
    }

    /// One initial actor inside a Create: `[actorId, authenticator, scope,
    /// policyData]`. Measured against three real creations on this chain.
    struct InitialActor: Equatable {
        var actorID: Data
        var authenticator: Data
        var scope: UInt64
        var policyData: Data
        var item: Item {
            .list([.bytes(actorID), .bytes(authenticator),
                   .bytes(quantity(scope)), .bytes(policyData)])
        }
    }

    /// A CREATE entry: `rlp([0x00, userSalt, code, initialActors])`.
    ///
    /// **The account signs its OWN creation** — `sender` is the counterfactual
    /// account and `sender_auth` is its first actor's signature. Measured, not
    /// assumed: all seven creations on this chain are shaped that way and three
    /// of them are signed by a P-256 key. That is what makes "Face ID is the
    /// key" true end to end, with no ordinary wallet needed anywhere.
    struct CreateAccount: Equatable {
        var userSalt: Data
        var code: Data
        var initialActors: [InitialActor]
        var item: Item {
            .list([.bytes(quantity(0x00)), .bytes(userSalt), .bytes(code),
                   .list(initialActors.map(\.item))])
        }
    }

    /// An account-changes entry is one or the other. An enum rather than two
    /// arrays so a caller cannot accidentally emit both in an order the hash
    /// would notice.
    enum AccountChange: Equatable {
        case create(CreateAccount)
        case config(ConfigChange)
        var item: Item {
            switch self {
            case .create(let c): c.item
            case .config(let c): c.item
            }
        }
    }

    /// A config-change entry: `rlp([0x01, channel, sequence, changes, auth])`.
    /// `channel` is 0 for Local — also measured rather than assumed.
    struct ConfigChange: Equatable {
        var channel: UInt64 = 0
        var sequence: UInt64
        var changes: [Change]
        var auth: Data
        var item: Item {
            .list([.bytes(quantity(0x01)), .bytes(quantity(channel)),
                   .bytes(quantity(sequence)),
                   .list(changes.map(\.item)), .bytes(auth)])
        }
    }

    /// The fields the sender signs over. Deliberately a value type with no
    /// defaults for the money-shaped fields: a gas limit that defaults to zero
    /// is a transaction that cannot run, and one that defaults to something
    /// plausible is worse.
    struct Fields: Equatable {
        var chainID: UInt64
        /// Empty for an EOA sender. A populated sender means a configured
        /// actor, whose `sender_auth` this app cannot yet compose.
        var sender: Data = Data()
        var nonceKey: UInt64 = 0
        var nonceSequence: UInt64
        var validAfter: UInt64 = 0
        var validBefore: UInt64 = 0
        var maxPriorityFeePerGas: UInt64
        var maxFeePerGas: UInt64
        var gasLimit: UInt64
        var accountChanges: [AccountChange] = []
        /// Phases of calls. Empty is legal.
        var calls: [[Call]] = []
        var metadata: Data = Data()
        /// Empty unless somebody else is paying — this is the wire form of the
        /// Sponsorship the console offers as a feature card.
        var payer: Data = Data()
    }

    /// The list the SENDER hash covers: everything through `payer`, with both
    /// auth fields excluded. Shared with the full-transaction encoder so the
    /// two can never disagree about field order — which is exactly the drift
    /// that produces a signature over a different transaction.
    static func signingBody(_ f: Fields) -> [Item] {
        [.bytes(quantity(f.chainID)),
         .bytes(f.sender),
         .bytes(quantity(f.nonceKey)),
         .bytes(quantity(f.nonceSequence)),
         .bytes(quantity(f.validAfter)),
         .bytes(quantity(f.validBefore)),
         .bytes(quantity(f.maxPriorityFeePerGas)),
         .bytes(quantity(f.maxFeePerGas)),
         .bytes(quantity(f.gasLimit)),
         .list(f.accountChanges.map(\.item)),
         .list(f.calls.map { phase in Item.list(phase.map(\.item)) }),
         .bytes(f.metadata),
         .bytes(f.payer)]
    }

    /// THE BYTES THAT GET BROADCAST: `AA_TX_TYPE || rlp([...through payer,
    /// sender_auth, payer_auth])` — the signing body with the two auth fields
    /// appended, ready for `eth_sendRawTransaction`.
    ///
    /// **This is a WEAKER claim than `senderSigningPreimage`, and the
    /// difference matters more than it looks.** That function's field order is
    /// proven: re-encoding real transactions and recovering their signers
    /// passes 3/3, so a mistake there is impossible to miss. The two trailing
    /// fields cannot be proven that way — they are excluded from the hash by
    /// definition, so no recovery can see them, and this node refuses every
    /// raw-transaction read (403), so there is no encoded example to compare
    /// against. Their order comes from the spec alone.
    ///
    /// **That is survivable precisely because it fails LOUDLY.** A wrong
    /// signing hash produces a valid signature over the wrong transaction —
    /// silent, and somebody else's money. A wrong broadcast envelope is
    /// rejected by the node with an error, before anything happens. The first
    /// class had to be proven; the second announces itself the first time it is
    /// tried, which is the whole reason to try it on a devnet.
    static func encoded(_ f: Fields, senderAuth: Data, payerAuth: Data = Data()) -> Data {
        Data([txType]) + encode(.list(signingBody(f)
                                      + [.bytes(senderAuth), .bytes(payerAuth)]))
    }

    /// `AA_TX_TYPE || rlp([...through payer])` — the bytes that get hashed.
    /// Returned rather than hashed here so the harness can pin the PREIMAGE
    /// too: a hash fixture alone cannot say which of two encodings produced
    /// it, and the preimage length was one of the things the proof turned on.
    static func senderSigningPreimage(_ f: Fields) -> Data {
        Data([txType]) + encode(.list(signingBody(f)))
    }
}

// MARK: - Moving value: the self-call into `DefaultAccount.execute`

/// HOW ETH ACTUALLY MOVES (2026-08-31).
///
/// The wire-level `Call` above is deliberately `(to, data)` with no value —
/// confirmed against the EIP-8130 spec text ("Calls carry no ETH value. ETH
/// transfers are initiated by the account's wallet bytecode via the CALL
/// opcode") and against the reference `DefaultAccount.sol` (Coinbase,
/// `base/eip-8130`): `executeBatch`/`execute` take `(target, value, data)`
/// triples and do the real value-carrying `target.call{value: value}(data)`.
///
/// So a plain send is a SELF-CALL: the top-level wire `Call.to` is the
/// account's OWN address, and `Call.data` is `execute(address,uint256,bytes)`
/// aimed at the real recipient. `DefaultAccount._isAuthorizedCaller` passes
/// trivially (`caller == address(this)`) because the account is executing
/// this call as itself — no actor check, no scope check, nothing this app
/// needs to reason about beyond composing the right calldata.
///
/// `execute(address,uint256,bytes)` selector is `0xb61d27f6`, computed from
/// the signature text (keccak256, first 4 bytes) rather than pasted — the
/// same discipline `SafeCalldata.selector` already keeps for its own
/// selectors, and for the identical reason: a mistyped constant here names a
/// different function and every send would revert with no clue why.
/// SHARED SOLIDITY-ABI WORD ENCODING (2026-08-31). `VibenetExecute` and
/// `VibenetAccountChanges` both build plain `abi.encode`-shaped calldata —
/// static head words, a dynamic `bytes` tail — and a word is a word
/// regardless of which function it's arguing for, so the padding logic lives
/// once here rather than twice.
enum VibenetABIEncode {
    /// A big-endian byte string, left-padded to 32 bytes — the ABI's static
    /// word shape for an address (20 bytes), a `bytes32` already 32 bytes,
    /// and a value carried as raw big-endian bytes (never a machine int:
    /// `Fields`' own money fields are `UInt64`, too small for a wei amount
    /// past ~18.4 ETH, so callers hand this raw bytes rather than a type that
    /// silently truncates a real balance).
    static func word(_ bytes: Data) -> Data {
        guard bytes.count <= 32 else { return Data(bytes.suffix(32)) }
        return Data(repeating: 0, count: 32 - bytes.count) + bytes
    }

    static func word(_ n: UInt64) -> Data {
        var be = Data(count: 8)
        var v = n
        for i in stride(from: 7, through: 0, by: -1) { be[i] = UInt8(v & 0xff); v >>= 8 }
        return word(be)
    }

    /// A dynamic `bytes` tail, zero-padded to a 32-byte multiple — the
    /// suffix every ABI-encoded call with a trailing `bytes`/`string` param
    /// carries after its length word.
    static func padded(_ data: Data) -> Data {
        let pad = (32 - data.count % 32) % 32
        return pad > 0 ? data + Data(repeating: 0, count: pad) : data
    }
}

enum VibenetExecute {
    /// `keccak256("execute(address,uint256,bytes)")[:4]`.
    static let selector: Data = Data(Keccak256.hash(Array("execute(address,uint256,bytes)".utf8)).prefix(4))

    /// Static ABI head (address, uint256, offset-to-bytes) then the dynamic
    /// `bytes` tail — the ordinary Solidity ABI layout for
    /// `execute(address,uint256,bytes)`. `data` is empty for a plain value
    /// transfer (a contract call through this same door is future work, not
    /// this one — see `VibenetSend.sendValue`'s own doc).
    static func calldata(target: Data, value: Data, data: Data = Data()) -> Data {
        var out = selector
        out += VibenetABIEncode.word(target)
        out += value.count == 32 ? value : VibenetABIEncode.word(value)
        out += VibenetABIEncode.word(UInt64(0x60))   // offset to the bytes tail
        out += VibenetABIEncode.word(UInt64(data.count))
        out += VibenetABIEncode.padded(data)
        return out
    }

    /// Big-endian wei bytes as a decimal ETH string ("1.5", "0.000000000123",
    /// "1000000000"), never `Double` — this app's own 1B-ETH devnet faucet
    /// balances are already past `Double`'s exact-integer range, so a
    /// receipt's stated amount would silently drift from what was actually
    /// signed. Base-256-to-base-10 by repeated long division on a decimal
    /// digit array — the textbook bignum-free conversion, since nothing here
    /// needs arbitrary-precision arithmetic beyond printing one number once.
    static func decimalEther(weiBigEndian: Data) -> String {
        guard !weiBigEndian.isEmpty else { return "0" }
        var digits: [UInt8] = [0]
        for byte in weiBigEndian {
            var carry = UInt16(byte)
            for i in (0..<digits.count).reversed() {
                let v = UInt16(digits[i]) * 256 + carry
                digits[i] = UInt8(v % 10)
                carry = v / 10
            }
            while carry > 0 { digits.insert(UInt8(carry % 10), at: 0); carry /= 10 }
        }
        var s = digits.map { String($0) }.joined()
        while s.count < 19 { s = "0" + s }
        let splitAt = s.index(s.endIndex, offsetBy: -18)
        var whole = String(s[s.startIndex..<splitAt])
        var frac = String(s[splitAt...])
        while whole.count > 1, whole.hasPrefix("0") { whole.removeFirst() }
        while frac.hasSuffix("0") { frac.removeLast() }
        return frac.isEmpty ? whole : "\(whole).\(frac)"
    }
}

// MARK: - Authorizing and revoking actors — the OTHER signature

/// WHAT `ConfigChange.auth` ACTUALLY SIGNS (2026-08-31, prd §534).
///
/// **Read from `Keystore.sol` (Coinbase, `base/eip-8130`), not guessed** —
/// exactly the lesson `VibenetDeviceKey.sign`'s own history exists to teach:
/// a plausible preimage produces a signature that is valid arithmetic and
/// authenticates NOTHING, failing silently on-chain while every static check
/// here stays green.
///
/// The source's own doc says the scheme is deliberately **NOT EIP-712**
/// ("to mitigate phishing attacks") — no domain separator, no `\x19\x01`
/// prefix. It is a flat, two-level typed hash:
///
///     changeHash = keccak256(abi.encode(ACCOUNT_CHANGE_TYPEHASH,
///                                       changeType, keccak256(payload)))
///     digest = keccak256(abi.encode(SIGNED_ACCOUNT_CHANGES_TYPEHASH,
///                                   account, chainId, sequence,
///                                   keccak256(concat(changeHashes))))
///
/// `sequence` is the account's CURRENT counter, not the next one — the
/// contract checks it matches before advancing it — and for the Local
/// channel (`channel: 0`, the only one this app ever uses) it is the packed
/// word `localEpoch(32, high) || localSequence(32, low)`, already sitting on
/// `VibenetAccountItem.changeSequences` from the ordinary account read; this
/// never costs a request of its own.
///
/// **Authorization is flat and admin-only** — `Keystore.
/// applySignedAccountChanges` requires the signer's scope to be exactly 0,
/// which is what every account this app has ever created uses for its one
/// key, so no new scope work is needed to authorize or revoke a second one.
///
/// `auth` itself is the ordinary `authenticator(20) || data` blob every
/// other signature in this file already wears — `VibenetP256Auth.senderAuth`
/// is reused verbatim, not reimplemented.
enum VibenetAccountChanges {
    /// `Keystore.sol`'s `ChangeType` enum, declaration order.
    static let authorizeActor: UInt8 = 0
    static let revokeActor: UInt8 = 1

    static let accountChangeTypeHash: Data =
        Data(Keccak256.hash(Array("AccountChange(uint8 changeType,bytes payload)".utf8)))

    static let signedAccountChangesTypeHash: Data = Data(Keccak256.hash(Array(
        ("SignedAccountChanges(address account,uint256 chainId,uint64 sequence,AccountChange[] changes)"
         + "AccountChange(uint8 changeType,bytes payload)").utf8)))

    /// `abi.encode(bytes32 actorId, ActorConfig(authenticator,expiry,scope), bytes policyData)`.
    /// `ActorConfig` is entirely static fields, so it inlines as three head
    /// words rather than taking an offset of its own — the same rule that
    /// makes `execute`'s `(address,uint256,bytes)` head three words before
    /// its own dynamic tail. `policyData` stays empty for a plain P-256
    /// actor (§523's own `scope: 0`, empty `policyData` convention) —
    /// non-empty policy grants are Subscriptions' problem, not this one's.
    static func authorizeActorPayload(actorId: Data, authenticator: Data,
                                      expiry: UInt64 = 0, scope: UInt16 = 0,
                                      policyData: Data = Data()) -> Data {
        var out = VibenetABIEncode.word(actorId)
        out += VibenetABIEncode.word(authenticator)
        out += VibenetABIEncode.word(UInt64(expiry))
        out += VibenetABIEncode.word(UInt64(scope))
        out += VibenetABIEncode.word(UInt64(0xa0))   // offset to policyData: 5 head words × 32
        out += VibenetABIEncode.word(UInt64(policyData.count))
        out += VibenetABIEncode.padded(policyData)
        return out
    }

    /// `abi.encode(bytes32 actorId)` — the whole payload is one static word.
    static func revokeActorPayload(actorId: Data) -> Data { VibenetABIEncode.word(actorId) }

    /// One `AccountChange`'s structural hash.
    static func changeHash(changeType: UInt8, payload: Data) -> Data {
        var body = accountChangeTypeHash
        body += VibenetABIEncode.word(UInt64(changeType))
        body += Data(Keccak256.hash([UInt8](payload)))
        return Data(Keccak256.hash([UInt8](body)))
    }

    /// `_changesDigest` — the whole of what `ConfigChange.auth` signs.
    /// `chainID` is this app's own `UInt64` (vibenet's real id is nowhere
    /// near `UInt256`'s range, so no truncation risk in padding it up).
    static func changesDigest(account: Data, chainID: UInt64, sequence: UInt64,
                              changeHashes: [Data]) -> Data {
        let packed = changeHashes.reduce(Data(), +)
        let hashesHash = Data(Keccak256.hash([UInt8](packed)))
        var body = signedAccountChangesTypeHash
        body += VibenetABIEncode.word(account)
        body += VibenetABIEncode.word(UInt64(chainID))
        body += VibenetABIEncode.word(UInt64(sequence))
        body += hashesHash
        return Data(Keccak256.hash([UInt8](body)))
    }

    /// The Local-channel sequence word — `localEpoch<<32 | localSequence`.
    /// Takes the two halves as plain integers rather than
    /// `VibenetChangeSequences` (defined in `VibenetRoom.swift`, which this
    /// file must stay independent of — `vibenet-signer-selftest.sh` compiles
    /// this file standalone, alongside only `Keccak256`/`VibenetCreate`/
    /// `VibenetSigner`/`RLP`). The caller reads both off
    /// `VibenetAccountItem.changeSequences` for free — no new request.
    static func localSequenceWord(epoch: UInt32, sequence: UInt32) -> UInt64 {
        (UInt64(epoch) << 32) | UInt64(sequence)
    }
}

// MARK: - The P-256 authenticator's wire format

/// HOW A P-256 KEY AUTHENTICATES, MEASURED AGAINST THE CONTRACT ITSELF
/// (prd §523, 2026-08-29).
///
/// The spec says a configured actor's `sender_auth` is
/// `authenticator (20 bytes) || data` and leaves `data` **authenticator-
/// specific**. No P-256 actor has ever been authorized on this chain, so there
/// is no transaction to copy. The format below was not read off a document and
/// not inferred from the other authenticators — it was **asked of the deployed
/// contract**.
///
/// `P256Authenticator` exposes `authenticate(bytes32,bytes)` (selector
/// `0x30ba1adf`, recovered by hashing candidate signatures against the
/// selectors in its own bytecode). That is a view call, so a software P-256
/// key can sign a hash and every candidate layout can be tried against the
/// real contract for the price of an `eth_call`. Measured:
///
///   • `r || s || x || y` (128 bytes) — **reverts**
///   • `r || s || x || y || <1 byte>` (129) — **returns a non-zero word**
///   • 130 and 160 bytes — **revert**
///
/// so the length is checked exactly and **129 is the format**. The trailing
/// byte's VALUE is ignored (0x00 through 0xff all answer identically), which
/// is why `padByte` is a zero rather than something that looks meaningful:
/// nothing here should imply a field that the contract does not read.
///
/// **The word it returns is the actor id**, and that was measured too rather
/// than assumed: the same key over two different messages returns the same
/// word, two different keys return different words, and a signature presented
/// for the wrong message returns **zero** — so a non-zero answer is a real
/// verification, not an echo. The word equals `keccak256(x || y)`, confirmed
/// independently for two keys.
///
/// **This is the join `VibenetSigner` needed**, and it is better than reading
/// `actorData` back: an account accepts this phone when it authorizes
/// `actorID(publicKey:)`. It stays a CANONICAL id rather than the only one —
/// the id is caller-supplied at authorize time (see the type doc above), so
/// another client may have registered the same key under a different word, and
/// a nil answer from a lookup still means cannot-say rather than no.
enum VibenetP256Auth {

    /// Measured: any value answers identically, so this is padding to reach the
    /// length the contract checks, and nothing more.
    static let padByte: UInt8 = 0x00

    /// The exact byte count `authenticate` accepts. 128 and 130 both revert, so
    /// this is not a minimum — it is the length.
    static let dataLength = 129

    /// `r || s || x || y || pad`. **Order is measured**: `x || y || r || s`
    /// reverts at this length, so a transposition here is not a stylistic
    /// choice, it is a signature the chain refuses.
    static func authData(r: Data, s: Data, publicKeyXY: Data) -> Data? {
        guard r.count == 32, s.count == 32, publicKeyXY.count == 64 else { return nil }
        return r + s + publicKeyXY + Data([padByte])
    }

    /// `authenticator || data` — what rides `sender_auth` for a configured
    /// actor. 149 bytes.
    static func senderAuth(authenticator: Data, r: Data, s: Data, publicKeyXY: Data) -> Data? {
        guard authenticator.count == 20,
              let data = authData(r: r, s: s, publicKeyXY: publicKeyXY) else { return nil }
        return authenticator + data
    }

    /// `keccak256(x || y)` — the id the contract itself answers with.
    ///
    /// Deliberately NOT `keccak256(0x04 || x || y)`: the uncompressed-point tag
    /// is how a public key is usually framed and it produces a different,
    /// plausible-looking word that the contract does not agree with. Measured
    /// both ways.
    static func actorID(publicKeyXY: Data) -> Data? {
        guard publicKeyXY.count == 64 else { return nil }
        return Data(Keccak256.hash([UInt8](publicKeyXY)))
    }
}

// MARK: - Where a new account will live

/// THE COUNTERFACTUAL ACCOUNT ADDRESS (prd §523, 2026-08-29).
///
/// A creation sets `sender` to the new account's address BEFORE it exists, so
/// the address is computed client-side and everything downstream depends on
/// getting it right: it is signed over, so a wrong one is not a wrong guess but
/// a signature over a different transaction.
///
/// **Two hidden layers made this resist a long search**, and both are the kind
/// that produce a plausible wrong answer rather than an obvious one:
///
/// 1. The actors are folded through **per-actor leaf hashes, then a hash of the
///    concatenated leaves** — not a flat concatenation and not their RLP.
/// 2. The CREATE2 init-code hash is **not** `keccak256(code)`. It is
///    `keccak256(DEPLOYMENT_HEADER ‖ code)`. `AccountCreated`'s second word IS
///    `keccak256(code)`, which makes it a decoy: it is right there in the event,
///    it looks like exactly the value CREATE2 wants, and it is the wrong one.
///
/// `scope` is **two bytes, big-endian** inside the leaf. Proven rather than
/// assumed: the deployed `Keystore.computeAddress` (selector `0x500fa70e`)
/// agrees with this computation byte for byte on a fresh parameter set, and a
/// one-byte encoding would disagree.
///
/// Verified three ways: all **7/7** creations on this chain reproduce; the node
/// itself accepts a derived sender (a wrong one is refused with "create address
/// does not match the sender", a right one advances to "insufficient funds");
/// and the Keystore's own view function returns the same word.
enum VibenetAddress {

    /// The 14-byte constructor that returns `code` as the deployed body.
    /// `61 <n:2> 60 0E 60 00 39 61 <n:2> 60 00 F3`.
    static func deploymentHeader(codeLength: Int) -> Data? {
        guard codeLength > 0, codeLength <= 0xffff else { return nil }
        let n = UInt16(codeLength)
        let hi = UInt8(n >> 8), lo = UInt8(n & 0xff)
        return Data([0x61, hi, lo, 0x60, 0x0E, 0x60, 0x00, 0x39, 0x61, hi, lo, 0x60, 0x00, 0xF3])
    }

    /// `keccak256(actorId ‖ authenticator ‖ scope(2, BE) ‖ policyData)`.
    static func leaf(_ a: VibenetTransaction.InitialActor) -> Data? {
        guard a.actorID.count == 32, a.authenticator.count == 20,
              a.scope <= UInt64(UInt16.max) else { return nil }
        let scope = UInt16(a.scope)
        let bytes = a.actorID + a.authenticator
            + Data([UInt8(scope >> 8), UInt8(scope & 0xff)]) + a.policyData
        return Data(Keccak256.hash([UInt8](bytes)))
    }

    /// Where the account will be.
    ///
    /// **Actors are sorted strictly ascending by `actorId`** — the commitment is
    /// order-dependent, so an unsorted list yields a different, perfectly
    /// valid-looking address that the node then refuses. Sorted here rather than
    /// demanded of the caller: a rule the caller has to remember is one that
    /// eventually is not.
    static func derive(keystore: Data,
                       userSalt: Data,
                       code: Data,
                       initialActors: [VibenetTransaction.InitialActor]) -> Data? {
        guard keystore.count == 20, userSalt.count == 32, !initialActors.isEmpty,
              let header = deploymentHeader(codeLength: code.count) else { return nil }
        var leaves = Data()
        for actor in initialActors.sorted(by: { $0.actorID.lexicographicallyPrecedes($1.actorID) }) {
            guard let l = leaf(actor) else { return nil }
            leaves += l
        }
        let commitment = Data(Keccak256.hash([UInt8](leaves)))
        let effectiveSalt = Data(Keccak256.hash([UInt8](userSalt + commitment)))
        let initCodeHash = Data(Keccak256.hash([UInt8](header + code)))
        let word = Keccak256.hash([UInt8](Data([0xff]) + keystore + effectiveSalt + initCodeHash))
        return Data(word.suffix(20))
    }
}
