// Generated by scripts/walletbeat-snapshot.py — DO NOT EDIT BY HAND.
//
// Walletbeat's ratings for every wallet it rates, distilled to the counts a list
// row draws. Regenerate at ship time; `scripts/walletbeat-snapshot.py --check`
// fails the build when this file no longer matches what Walletbeat publishes.
//
// These are WALLETBEAT'S judgments, not ours. Nothing here ranks wallets or sums a
// dimension into a score — a composite is an editorial act Walletbeat itself
// declines to make (prd §419).

import Foundation

enum WalletbeatDirectory {
	/// The day this snapshot was taken from beta.walletbeat.eth.limo.
	static let generated = "2026-08-20"

	static let wallets: [WalletbeatEntry] = [
		WalletbeatEntry(
			id: "ambire",
			name: "Ambire",
			hardware: false,
			variants: ["browser"],
			stage: "Stage 0",
			updated: "2026-07-22",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 3, fail: 3, unrated: 0, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 2, fail: 3, unrated: 0, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 3, partial: 0, fail: 2, unrated: 0, exempt: 0), .transparency: WalletbeatCounts(pass: 3, partial: 2, fail: 0, unrated: 0, exempt: 0), .ecosystem: WalletbeatCounts(pass: 4, partial: 2, fail: 0, unrated: 0, exempt: 0)]
		),
		WalletbeatEntry(
			id: "base-app",
			name: "Base App",
			hardware: false,
			variants: ["mobile"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2026-03-19",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 1, fail: 3, unrated: 4, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 4, unrated: 1, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 1, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 2, partial: 2, fail: 0, unrated: 0, exempt: 0)]
		),
		WalletbeatEntry(
			id: "bitbox",
			name: "BitBox",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-01-07",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "bitget",
			name: "Bitget Wallet",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2026-01-17",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 2, partial: 0, fail: 1, unrated: 2, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 1, fail: 1, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 1, fail: 2, unrated: 2, exempt: 0)]
		),
		WalletbeatEntry(
			id: "mtpelerin",
			name: "Bridge Wallet",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2025-08-26",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0)]
		),
		WalletbeatEntry(
			id: "cypherock",
			name: "Cypherock Wallet",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-01-06",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 1, fail: 0, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "daimo",
			name: "Daimo",
			hardware: false,
			variants: ["mobile"],
			stage: "Stage 0",
			updated: "2025-03-12",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 2, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 2, unrated: 2, exempt: 0), .transparency: WalletbeatCounts(pass: 2, partial: 0, fail: 0, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 1, fail: 1, unrated: 0, exempt: 0)]
		),
		WalletbeatEntry(
			id: "elytro",
			name: "Elytro",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2025-03-12",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0)]
		),
		WalletbeatEntry(
			id: "family",
			name: "Family",
			hardware: false,
			variants: ["mobile"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2025-04-22",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 3, exempt: 0)]
		),
		WalletbeatEntry(
			id: "firefly",
			name: "Firefly Wallet",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-03-12",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "frame",
			name: "Frame",
			hardware: false,
			variants: ["desktop", "browser"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2025-03-13",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 0, fail: 1, unrated: 4, exempt: 0)]
		),
		WalletbeatEntry(
			id: "gemwallet",
			name: "Gem Wallet",
			hardware: false,
			variants: ["mobile"],
			stage: "Stage 0",
			updated: "2025-10-14",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .transparency: WalletbeatCounts(pass: 2, partial: 0, fail: 0, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 1, fail: 1, unrated: 3, exempt: 0)]
		),
		WalletbeatEntry(
			id: "gridplus",
			name: "GridPlus Wallet",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-03-12",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 1, fail: 0, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 1, fail: 0, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 2, partial: 0, fail: 0, unrated: 3, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 3, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "imkey",
			name: "imKey",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-10-30",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 1, unrated: 2, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 3, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "imtoken",
			name: "imToken",
			hardware: false,
			variants: ["mobile"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2025-10-28",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 1, fail: 1, unrated: 5, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 1, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 2, fail: 2, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "keycard-shell",
			name: "Keycard Shell",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2026-05-02",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 3, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "keystone",
			name: "Keystone Wallet",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-03-12",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 1, fail: 0, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "ledger",
			name: "Ledger Wallet",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-03-12",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 1, fail: 0, unrated: 3, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "metamask",
			name: "MetaMask",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "Stage 0",
			updated: "2026-05-06",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 4, fail: 3, unrated: 0, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 2, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 2, partial: 1, fail: 2, unrated: 0, exempt: 0), .transparency: WalletbeatCounts(pass: 2, partial: 1, fail: 1, unrated: 1, exempt: 0), .ecosystem: WalletbeatCounts(pass: 4, partial: 2, fail: 0, unrated: 0, exempt: 0)]
		),
		WalletbeatEntry(
			id: "ngrave",
			name: "NGRAVE Zero",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-01-07",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "nufi",
			name: "NuFi",
			hardware: false,
			variants: ["browser"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2025-08-11",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 0, fail: 1, unrated: 5, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 1, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 4, partial: 0, fail: 1, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "okx",
			name: "OKX Wallet",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2026-01-28",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 8, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 1, unrated: 3, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 3, partial: 0, fail: 1, unrated: 2, exempt: 0)]
		),
		WalletbeatEntry(
			id: "onekey",
			name: "OneKey Pro",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-01-06",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 1, fail: 0, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "phantom",
			name: "Phantom",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "QUALIFIED_FOR_NO_STAGES",
			updated: "2025-02-08",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 2, unrated: 4, exempt: 0)]
		),
		WalletbeatEntry(
			id: "pillarx",
			name: "PillarX",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "Stage 0",
			updated: "2025-12-16",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 0, fail: 1, unrated: 3, exempt: 0)]
		),
		WalletbeatEntry(
			id: "rabby",
			name: "Rabby",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "Stage 0",
			updated: "2026-07-20",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 2, fail: 5, unrated: 0, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 2, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 2, partial: 0, fail: 3, unrated: 0, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 1, fail: 2, unrated: 1, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 2, fail: 3, unrated: 0, exempt: 0)]
		),
		WalletbeatEntry(
			id: "rainbow",
			name: "Rainbow",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "Stage 0",
			updated: "2026-08-02",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 1, fail: 6, unrated: 0, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 2, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 2, partial: 1, fail: 2, unrated: 0, exempt: 0), .transparency: WalletbeatCounts(pass: 3, partial: 1, fail: 0, unrated: 1, exempt: 0), .ecosystem: WalletbeatCounts(pass: 2, partial: 3, fail: 1, unrated: 0, exempt: 0)]
		),
		WalletbeatEntry(
			id: "safe",
			name: "Safe",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "Stage 0",
			updated: "2025-03-12",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 2, partial: 0, fail: 1, unrated: 2, exempt: 0), .transparency: WalletbeatCounts(pass: 2, partial: 0, fail: 0, unrated: 3, exempt: 0), .ecosystem: WalletbeatCounts(pass: 2, partial: 1, fail: 0, unrated: 3, exempt: 0)]
		),
		WalletbeatEntry(
			id: "trezor",
			name: "Trezor Wallet",
			hardware: true,
			variants: ["hardware"],
			stage: nil,
			updated: "2025-03-12",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 7, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 4, exempt: 0), .maintenance: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 1, exempt: 0)]
		),
		WalletbeatEntry(
			id: "uniswap-wallet",
			name: "Uniswap Wallet",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "Stage 0",
			updated: "2026-04-04",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 8, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 5, exempt: 0), .transparency: WalletbeatCounts(pass: 1, partial: 0, fail: 0, unrated: 4, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 0, fail: 0, unrated: 6, exempt: 0)]
		),
		WalletbeatEntry(
			id: "zerion",
			name: "Zerion",
			hardware: false,
			variants: ["mobile", "browser"],
			stage: "Stage 0",
			updated: "2026-08-10",
			counts: [.security: WalletbeatCounts(pass: 1, partial: 2, fail: 5, unrated: 0, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 4, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 2, partial: 0, fail: 3, unrated: 0, exempt: 0), .transparency: WalletbeatCounts(pass: 3, partial: 1, fail: 0, unrated: 1, exempt: 0), .ecosystem: WalletbeatCounts(pass: 1, partial: 2, fail: 3, unrated: 0, exempt: 0)]
		),
		WalletbeatEntry(
			id: "zeus",
			name: "Zeus",
			hardware: false,
			variants: ["desktop"],
			stage: "Stage 0",
			updated: "2026-01-12",
			counts: [.security: WalletbeatCounts(pass: 0, partial: 0, fail: 1, unrated: 6, exempt: 0), .privacy: WalletbeatCounts(pass: 0, partial: 0, fail: 2, unrated: 3, exempt: 0), .selfSovereignty: WalletbeatCounts(pass: 2, partial: 1, fail: 1, unrated: 1, exempt: 0), .transparency: WalletbeatCounts(pass: 2, partial: 1, fail: 0, unrated: 2, exempt: 0), .ecosystem: WalletbeatCounts(pass: 0, partial: 1, fail: 1, unrated: 3, exempt: 0)]
		),
	]

	/// The demo corpus's wallets, with Walletbeat's real ratings and real
	/// sentences — so the furnished demo shows what the feature actually shows.
	static let demoAttributes: [String: [WalletbeatAttribute]] = [
		"ledger": [
			WalletbeatAttribute(id: "accountRecovery", dimension: .security, name: "Account recovery", question: "How easy does the wallet make it to recover your account?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "duressResistance", dimension: .security, name: "Duress resistance", question: "Does Ledger Wallet protect users from being physically coerced into surrendering their funds?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "firmware", dimension: .security, name: "Firmware", question: "Does Ledger Wallet have secure and open firmware?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "securityAuditsAndBounties", dimension: .security, name: "Security Audits & Bounties", question: "Has the wallet's source code been reviewed by security auditors, and does the wallet maintain an active bug bounty program?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "supplyChainFactory", dimension: .security, name: "Supply Chain Factory", question: "Does Ledger Wallet have a secure and transparent factory supply chain?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "transactionLegibility", dimension: .security, name: "Transaction legibility", question: "When signing a transaction, does the wallet show transaction details clearly?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "userSafety", dimension: .security, name: "User Safety", question: "Does Ledger Wallet provide comprehensive user safety features?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "addressCorrelation", dimension: .privacy, name: "Wallet address privacy", question: "Is your wallet address linkable to other information about yourself?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "hardwarePrivacy", dimension: .privacy, name: "Hardware Privacy", question: "Does Ledger Wallet protect user privacy at the hardware level?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "multiAddressCorrelation", dimension: .privacy, name: "Multi-address privacy", question: "Can your multiple wallet addresses be correlated with one another?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "privateTransfers", dimension: .privacy, name: "Private token transfers", question: "Can you send and receive tokens without revealing your transaction history to others?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "accountPortability", dimension: .selfSovereignty, name: "Account portability", question: "Are you locked into this wallet? Or can you permissionlessly import your Ethereum account into another wallet?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "accountUnruggability", dimension: .selfSovereignty, name: "Account unruggability", question: "Can the wallet developer take over your account without your consent?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "l1ProviderIndependence", dimension: .selfSovereignty, name: "L1 provider independence", question: "Can you use the wallet without relying on its default provider for interacting with the L1 chain?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "permissionsManagement", dimension: .selfSovereignty, name: "Permissions management", question: "Does Ledger Wallet let you inspect and manage the permissions you've granted to other contracts and apps?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "transactionInclusion", dimension: .selfSovereignty, name: "Transaction inclusion", question: "Can the wallet withdraw L2 funds to Ethereum L1 without relying on intermediaries?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "feeTransparency", dimension: .transparency, name: "Fee transparency", question: "Does the wallet clearly display all transaction fees and their purpose?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "funding", dimension: .transparency, name: "Funding", question: "How is the wallet's development team funded?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "openSource", dimension: .transparency, name: "Source code license", question: "Does the user have the ability to avoid lock-in and freely audit, modify, and redistribute the wallet's source code?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "reputation", dimension: .transparency, name: "Reputation", question: "Does Ledger Wallet have a strong reputation for reliability and transparency?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "accountAbstraction", dimension: .ecosystem, name: "Account abstraction", question: "Is the wallet Account Abstraction ready?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "addressResolution", dimension: .ecosystem, name: "Address resolution", question: "Can you send funds to human-readable Ethereum addresses?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "appConnectionSupport", dimension: .ecosystem, name: "app Connection Support", question: "Can the hardware wallet connect to web3 applications?", verdict: .partial, explanation: "Ledger Wallet can connect to some apps using verifiable code or open standards, but with limitations."),
			WalletbeatAttribute(id: "interoperability", dimension: .ecosystem, name: "Interoperability", question: "Does Ledger Wallet work well with independent wallets and avoid supplier linkage?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "maintenance", dimension: .maintenance, name: "Maintenance", question: "Does Ledger Wallet have good maintenance practices?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
		],
		"metamask": [
			WalletbeatAttribute(id: "accountRecovery", dimension: .security, name: "Account recovery", question: "How easy does the wallet make it to recover your account?", verdict: .fail, explanation: "MetaMask's account recovery feature cannot be relied upon in multiple scenarios."),
			WalletbeatAttribute(id: "chainVerification", dimension: .security, name: "Chain verification", question: "Does the wallet verify the integrity of the chain(s) it interacts with?", verdict: .fail, explanation: "MetaMask does not verify chain integrity of the Ethereum L1."),
			WalletbeatAttribute(id: "duressResistance", dimension: .security, name: "Duress resistance", question: "Does MetaMask protect users from being physically coerced into surrendering their funds?", verdict: .partial, explanation: "MetaMask has a lock screen (password and biometric (Face ID / fingerprint)) but no duress mode."),
			WalletbeatAttribute(id: "hardwareWalletSupport", dimension: .security, name: "Hardware wallet support", question: "Does the wallet support connecting to hardware wallets?", verdict: .pass, explanation: "MetaMask supports hardware wallets."),
			WalletbeatAttribute(id: "scamPrevention", dimension: .security, name: "Scam prevention", question: "Does the wallet warn the user about potential scams?", verdict: .partial, explanation: "MetaMask warns the user about outgoing transactions to unknown addresses, transactions with potential scam contracts, and connections to potential scam applications but not about transactions that grant unlimited token approvals"),
			WalletbeatAttribute(id: "securityAuditsAndBounties", dimension: .security, name: "Security Audits & Bounties", question: "Has the wallet's source code been reviewed by security auditors, and does the wallet maintain an active bug bounty program?", verdict: .partial, explanation: "The most recent security audit for MetaMask is over a year old."),
			WalletbeatAttribute(id: "securityBestPractices", dimension: .security, name: "Security best practices", question: "Does MetaMask follow security best practices for key storage, random number generation, deployment hardening, and passkey verification?", verdict: .fail, explanation: "MetaMask requests high-risk OS permissions that are not necessary for a wallet."),
			WalletbeatAttribute(id: "transactionLegibility", dimension: .security, name: "Transaction legibility", question: "When signing a transaction, does the wallet show transaction details clearly?", verdict: .partial, explanation: "MetaMask supports partial transaction legibility."),
			WalletbeatAttribute(id: "addressCorrelation", dimension: .privacy, name: "Wallet address privacy", question: "Is your wallet address linkable to other information about yourself?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "appIsolation", dimension: .privacy, name: "App isolation", question: "If you connect to an app, will it be able to learn your past activity from other apps by default?", verdict: .fail, explanation: "MetaMask does not remember which set of addresses you last used when connecting to an app."),
			WalletbeatAttribute(id: "multiAddressCorrelation", dimension: .privacy, name: "Multi-address privacy", question: "Can your multiple wallet addresses be correlated with one another?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "privacyHygiene", dimension: .privacy, name: "Privacy hygiene", question: "Does MetaMask only send sensitive data with your explicit consent?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "privateTransfers", dimension: .privacy, name: "Private token transfers", question: "Can you send and receive tokens without revealing your transaction history to others?", verdict: .fail, explanation: "MetaMask does not support private token transfers."),
			WalletbeatAttribute(id: "accountPortability", dimension: .selfSovereignty, name: "Account portability", question: "Are you locked into this wallet? Or can you permissionlessly import your Ethereum account into another wallet?", verdict: .pass, explanation: "MetaMask follows EOA key derivation standards."),
			WalletbeatAttribute(id: "accountUnruggability", dimension: .selfSovereignty, name: "Account unruggability", question: "Can the wallet developer take over your account without your consent?", verdict: .pass, explanation: "MetaMask does not allow any external service to take over your account."),
			WalletbeatAttribute(id: "l1ProviderIndependence", dimension: .selfSovereignty, name: "L1 provider independence", question: "Can you use the wallet without relying on its default provider for interacting with the L1 chain?", verdict: .partial, explanation: "MetaMask contacts its default L1 RPC endpoint before letting you configure a self-hosted node."),
			WalletbeatAttribute(id: "permissionsManagement", dimension: .selfSovereignty, name: "Permissions management", question: "Does MetaMask let you inspect and manage the permissions you've granted to other contracts and apps?", verdict: .fail, explanation: "MetaMask does not support token approval management."),
			WalletbeatAttribute(id: "transactionInclusion", dimension: .selfSovereignty, name: "Transaction inclusion", question: "Can the wallet withdraw L2 funds to Ethereum L1 without relying on intermediaries?", verdict: .fail, explanation: "MetaMask requires trusting intermediaries in order to withdraw funds from L2s."),
			WalletbeatAttribute(id: "feeTransparency", dimension: .transparency, name: "Fee transparency", question: "Does the wallet clearly display all transaction fees and their purpose?", verdict: .pass, explanation: "MetaMask breaks down all transaction fees."),
			WalletbeatAttribute(id: "funding", dimension: .transparency, name: "Funding", question: "How is the wallet's development team funded?", verdict: .pass, explanation: "MetaMask is transparently funded."),
			WalletbeatAttribute(id: "openSource", dimension: .transparency, name: "Source code license", question: "Does the user have the ability to avoid lock-in and freely audit, modify, and redistribute the wallet's source code?", verdict: .fail, explanation: "MetaMask uses a proprietary license for some of its code."),
			WalletbeatAttribute(id: "orderflowTransparency", dimension: .transparency, name: "Orderflow transparency", question: "Does the wallet transparently disclose how it monetizes your transaction data?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "releaseProcess", dimension: .transparency, name: "Release process", question: "Can users trust that MetaMask's releases are built and distributed safely?", verdict: .partial, explanation: "MetaMask meets basic signals and partial advanced-group coverage."),
			WalletbeatAttribute(id: "accountAbstraction", dimension: .ecosystem, name: "Account abstraction", question: "Is the wallet Account Abstraction ready?", verdict: .pass, explanation: "MetaMask supports Account Abstraction via EIP-7702."),
			WalletbeatAttribute(id: "addressResolution", dimension: .ecosystem, name: "Address resolution", question: "Can you send funds to human-readable Ethereum addresses?", verdict: .partial, explanation: "MetaMask supports sending to plain ENS addresses but not chain-specific human-readable addresses."),
			WalletbeatAttribute(id: "browserIntegration", dimension: .ecosystem, name: "Browser integration", question: "Does the wallet comply with web browser integration standards?", verdict: .pass, explanation: "MetaMask supports all the prominent standards for web browser integration."),
			WalletbeatAttribute(id: "chainAbstraction", dimension: .ecosystem, name: "Chain abstraction", question: "Does the wallet smooth out the complexities of dealing with multiple chains?", verdict: .partial, explanation: "MetaMask does not add up token balances across chains."),
			WalletbeatAttribute(id: "hardwareWalletInteroperability", dimension: .ecosystem, name: "Hardware wallet interoperability", question: "Does the wallet support directly connecting to hardware wallets from a plurality of manufacturers?", verdict: .pass, explanation: "MetaMask supports a wide range of hardware wallets."),
			WalletbeatAttribute(id: "transactionBatching", dimension: .ecosystem, name: "Transaction batching", question: "Does the wallet support bundling multiple operations as a single transaction?", verdict: .pass, explanation: "MetaMask supports transaction batching and atomic transaction bundles."),
		],
		"rabby": [
			WalletbeatAttribute(id: "accountRecovery", dimension: .security, name: "Account recovery", question: "How easy does the wallet make it to recover your account?", verdict: .fail, explanation: "Rabby does not implement guardian-based account recovery. The user will lose access to their account if they lose their seed phrase."),
			WalletbeatAttribute(id: "chainVerification", dimension: .security, name: "Chain verification", question: "Does the wallet verify the integrity of the chain(s) it interacts with?", verdict: .fail, explanation: "Rabby does not verify chain integrity of the Ethereum L1."),
			WalletbeatAttribute(id: "duressResistance", dimension: .security, name: "Duress resistance", question: "Does Rabby protect users from being physically coerced into surrendering their funds?", verdict: .partial, explanation: "Rabby has a lock screen (password and biometric (Face ID / fingerprint)) but no duress mode."),
			WalletbeatAttribute(id: "hardwareWalletSupport", dimension: .security, name: "Hardware wallet support", question: "Does the wallet support connecting to hardware wallets?", verdict: .pass, explanation: "Rabby supports hardware wallets."),
			WalletbeatAttribute(id: "scamPrevention", dimension: .security, name: "Scam prevention", question: "Does the wallet warn the user about potential scams?", verdict: .fail, explanation: "Rabby warns you about potential scams, but leaks your browsed websites in the process."),
			WalletbeatAttribute(id: "securityAuditsAndBounties", dimension: .security, name: "Security Audits & Bounties", question: "Has the wallet's source code been reviewed by security auditors, and does the wallet maintain an active bug bounty program?", verdict: .fail, explanation: "The most recent security audit for Rabby is over a year old and some security flaws remain."),
			WalletbeatAttribute(id: "securityBestPractices", dimension: .security, name: "Security best practices", question: "Does Rabby follow security best practices for key storage, random number generation, deployment hardening, and passkey verification?", verdict: .fail, explanation: "Rabby requests overbroad permissions and does not restrict web-accessible resources."),
			WalletbeatAttribute(id: "transactionLegibility", dimension: .security, name: "Transaction legibility", question: "When signing a transaction, does the wallet show transaction details clearly?", verdict: .partial, explanation: "Rabby supports partial transaction legibility."),
			WalletbeatAttribute(id: "addressCorrelation", dimension: .privacy, name: "Wallet address privacy", question: "Is your wallet address linkable to other information about yourself?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "appIsolation", dimension: .privacy, name: "App isolation", question: "If you connect to an app, will it be able to learn your past activity from other apps by default?", verdict: .fail, explanation: "Rabby does not have an option to create a new account as part of the app connection flow."),
			WalletbeatAttribute(id: "multiAddressCorrelation", dimension: .privacy, name: "Multi-address privacy", question: "Can your multiple wallet addresses be correlated with one another?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "privacyHygiene", dimension: .privacy, name: "Privacy hygiene", question: "Does Rabby only send sensitive data with your explicit consent?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "privateTransfers", dimension: .privacy, name: "Private token transfers", question: "Can you send and receive tokens without revealing your transaction history to others?", verdict: .fail, explanation: "Rabby does not support private token transfers."),
			WalletbeatAttribute(id: "accountPortability", dimension: .selfSovereignty, name: "Account portability", question: "Are you locked into this wallet? Or can you permissionlessly import your Ethereum account into another wallet?", verdict: .pass, explanation: "Rabby follows EOA key derivation standards."),
			WalletbeatAttribute(id: "accountUnruggability", dimension: .selfSovereignty, name: "Account unruggability", question: "Can the wallet developer take over your account without your consent?", verdict: .pass, explanation: "Private key material never leaves Rabby, so no external entity may take over your account."),
			WalletbeatAttribute(id: "l1ProviderIndependence", dimension: .selfSovereignty, name: "L1 provider independence", question: "Can you use the wallet without relying on its default provider for interacting with the L1 chain?", verdict: .fail, explanation: "Even with your self-hosted node, Rabby depends on external services to perform basic tasks on Ethereum mainnet."),
			WalletbeatAttribute(id: "permissionsManagement", dimension: .selfSovereignty, name: "Permissions management", question: "Does Rabby let you inspect and manage the permissions you've granted to other contracts and apps?", verdict: .fail, explanation: "Rabby does not let you inspect or revoke token approvals."),
			WalletbeatAttribute(id: "transactionInclusion", dimension: .selfSovereignty, name: "Transaction inclusion", question: "Can the wallet withdraw L2 funds to Ethereum L1 without relying on intermediaries?", verdict: .fail, explanation: "Rabby requires trusting intermediaries in order to withdraw funds from L2s."),
			WalletbeatAttribute(id: "feeTransparency", dimension: .transparency, name: "Fee transparency", question: "Does the wallet clearly display all transaction fees and their purpose?", verdict: .fail, explanation: "Rabby hides some transaction fees."),
			WalletbeatAttribute(id: "funding", dimension: .transparency, name: "Funding", question: "How is the wallet's development team funded?", verdict: .pass, explanation: "Rabby is transparently funded."),
			WalletbeatAttribute(id: "openSource", dimension: .transparency, name: "Source code license", question: "Does the user have the ability to avoid lock-in and freely audit, modify, and redistribute the wallet's source code?", verdict: .fail, explanation: "Rabby uses a proprietary source code license."),
			WalletbeatAttribute(id: "orderflowTransparency", dimension: .transparency, name: "Orderflow transparency", question: "Does the wallet transparently disclose how it monetizes your transaction data?", verdict: .unrated, explanation: "Walletbeat lacks the information needed to determine this."),
			WalletbeatAttribute(id: "releaseProcess", dimension: .transparency, name: "Release process", question: "Can users trust that Rabby's releases are built and distributed safely?", verdict: .partial, explanation: "Rabby meets basic release-process signals but lacks advanced-group coverage."),
			WalletbeatAttribute(id: "accountAbstraction", dimension: .ecosystem, name: "Account abstraction", question: "Is the wallet Account Abstraction ready?", verdict: .fail, explanation: "Rabby supports EOAs only, with no Account Abstraction support."),
			WalletbeatAttribute(id: "addressResolution", dimension: .ecosystem, name: "Address resolution", question: "Can you send funds to human-readable Ethereum addresses?", verdict: .fail, explanation: "Rabby does not resolve human-readable addresses such as ENS names."),
			WalletbeatAttribute(id: "browserIntegration", dimension: .ecosystem, name: "Browser integration", question: "Does the wallet comply with web browser integration standards?", verdict: .pass, explanation: "Rabby supports all the prominent standards for web browser integration."),
			WalletbeatAttribute(id: "chainAbstraction", dimension: .ecosystem, name: "Chain abstraction", question: "Does the wallet smooth out the complexities of dealing with multiple chains?", verdict: .partial, explanation: "Rabby does not add up token balances across chains."),
			WalletbeatAttribute(id: "hardwareWalletInteroperability", dimension: .ecosystem, name: "Hardware wallet interoperability", question: "Does the wallet support directly connecting to hardware wallets from a plurality of manufacturers?", verdict: .partial, explanation: "Rabby supports a limited selection of hardware wallets."),
			WalletbeatAttribute(id: "transactionBatching", dimension: .ecosystem, name: "Transaction batching", question: "Does the wallet support bundling multiple operations as a single transaction?", verdict: .fail, explanation: "Rabby does not support transaction batching, as it does not support any type of smart account."),
		],
	]
}
