import UIKit

extension UIImage {
    /// Sample things carry bundled photos. Each demo shot has its own asset
    /// (sample:demo-shot-2 → sample-screenshot-2), so the demo photo grid
    /// shows four different images, never one repeated. Unnumbered or
    /// unknown refs fall back to the original sample.
    static func demoSample(for ref: String) -> UIImage? {
        // Product stills are their own family (2026-08-11). A `.product`
        // thing's sheet leads with its image, and pointing those at the
        // screenshot family showed a stock photo of a person where the
        // apron should be. Generated by `scripts/make-demo-product-art.swift`.
        if ref.hasPrefix("sample:product-") {
            let n = ref.replacingOccurrences(of: "sample:product-", with: "")
            return UIImage(named: "sample-product-\(n)")
        }
        let n = ref.replacingOccurrences(of: "sample:demo-shot-", with: "")
        return UIImage(named: "sample-screenshot-\(n)")
            ?? UIImage(named: "sample-screenshot")
    }
}
