import UIKit

extension UIImage {
    /// Sample things carry bundled photos. Each demo shot has its own asset
    /// (sample:demo-shot-2 → sample-screenshot-2), so the demo photo grid
    /// shows four different images, never one repeated. Unnumbered or
    /// unknown refs fall back to the original sample.
    static func demoSample(for ref: String) -> UIImage? {
        // The demo cast's faces (2026-08-11). Farcaster and Bluesky hydrate a
        // real `avatarURL` for every watched account and every landed post, so
        // a demo without them draws the source's brand glyph where the real
        // app draws people — three identical purple marks for three different
        // accounts. Generated by `scripts/make-demo-art.swift`.
        if ref.hasPrefix("sample:avatar-") {
            return UIImage(named: ref.replacingOccurrences(of: "sample:", with: "sample-"))
        }
        // Token marks (2026-08-12). `TokenWatch` stamps every watched token's
        // `previewImageURL` with the logo Dexscreener served, which both the
        // feed row and the watchlist roster draw as a circular face; a demo
        // without them falls to `BridgeIcon(name: "Tokens")`, so ETH, SOL and
        // DEGEN all wore the SAME green source glyph. These resolve to the
        // app's own shipped `brand-*` marks rather than generated art — the
        // real logos, so the room is indistinguishable from a connected one.
        if ref.hasPrefix("sample:token-") {
            let symbol = ref.replacingOccurrences(of: "sample:token-", with: "")
            return UIImage(named: "brand-\(symbol.lowercased())")
        }
        // Trending tokens get generated MONOGRAM marks, not brand assets —
        // `sample:token-` above resolves the three watched coins to the logos
        // this app already ships, but a trending row is somebody else's token
        // whose logo we have no right to reproduce. Same call the publication
        // marks make. Generated by `scripts/make-demo-art.swift`.
        if ref.hasPrefix("sample:coin-") {
            return UIImage(named: ref.replacingOccurrences(of: "sample:", with: "sample-"))
        }
        // Book covers, keyed by BOOK (2026-08-12). A Readwise highlight
        // carries the cover of the book it came from, so a real reading room
        // is a column of spines; the demo drew six identical source glyphs
        // for three books. Keyed rather than numbered because the demo quotes
        // each book more than once and one title must wear one cover.
        if ref.hasPrefix("sample:cover-") {
            return UIImage(named: ref.replacingOccurrences(of: "sample:", with: "sample-"))
        }
        // Stream frames — the Twitch hero's backdrop. Same reason as the
        // product stills: the bundled sample photos are of the real world,
        // and one of them under "Software and Game Development" put a
        // football stadium behind a dev stream.
        if ref.hasPrefix("sample:frame-") {
            let n = ref.replacingOccurrences(of: "sample:frame-", with: "")
            return UIImage(named: "sample-frame-\(n)")
        }
        // Product stills are their own family (2026-08-11). A `.product`
        // thing's sheet leads with its image, and pointing those at the
        // screenshot family showed a stock photo of a person where the
        // apron should be. Same generator.
        if ref.hasPrefix("sample:product-") {
            let n = ref.replacingOccurrences(of: "sample:product-", with: "")
            return UIImage(named: "sample-product-\(n)")
        }
        let n = ref.replacingOccurrences(of: "sample:demo-shot-", with: "")
        return UIImage(named: "sample-screenshot-\(n)")
            ?? UIImage(named: "sample-screenshot")
    }
}
