#!/usr/bin/env python3
"""The current-law digest (2026-10-01): which rulings in `docs/prd.md` are LIVE.

`docs/prd.md` is the append-only ruling ledger — a ruling that was reversed
stays exactly as written, so a dead entry looks exactly like a live one, and
"what is the rule today" means reading a chain. `docs/law.md` is the digest:
a hand-written "Current law by area" on top, and below it the MECHANICAL half
this script writes — every live ruling, one line, with the later rulings that
amend it.

WHERE "DEAD" COMES FROM — four sources, all inside the ledger itself:

  1. The Superseded index table (`| Ruling | What it said | Changed by |`).
  2. "Known stale, by hand" (rulings replaced without naming a number).
  3. "Renumbered entries" (a bare `| §236b | §236 | … |` row is a rename, not a
     change; the other rows that drifted into that table are read like 1/2).
  4. Each H2 heading's own parenthetical: "(…; supersedes §X, amends §Y)",
     "retires §Z", "reverses §W's one item", and the pre-§ spelling
     "supersedes 36a/36j".

THREE OUTCOMES, never two. A row or phrase that kills a ruling WHOLE removes it
from the live set. One that names a CLAUSE — "§548's tail order", "§983 item
2", "§306 (quiet hours)" where "quiet hours" is not §306's title, "superseded
in part", "for Polar only", "in the Wallet" — leaves the ruling live and marks
it "part superseded by §N", because guessing that a clause was the whole ruling
is how a live rule silently vanishes from the digest. Amend/extend/narrow is
always a chain link, never a death. Verb phrases INSIDE a parenthesis in an
index row are skipped: "(…; §775 is in turn superseded by §904)" is a fact
about §775 riding §772's row, not a fact about §772.

DELIBERATE NON-CHECKS:
  * It never reads an entry's BODY for supersede phrases. `prd-index-audit.py`
    check D already fails the build when a body names "supersedes §N" without an
    index row, so the index IS the body's claims, tabulated.
  * It cannot see a ruling quietly outgrown with no phrase anywhere. That is
    what the hand-written half above the marker and the "Known stale" table
    exist for.

Usage:
  python3 scripts/law-digest.py            rewrite docs/law.md below the marker
  python3 scripts/law-digest.py --check    exit 1 if law.md is stale, or if the
                                           hand-written half cites a ruling the
                                           ledger now says is dead
  python3 scripts/law-digest.py --self-test
  python3 scripts/law-digest.py --stats    counts only

Stdlib only.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LEDGER = ROOT / "docs" / "prd.md"
LAW = ROOT / "docs" / "law.md"
MARKER = "<!-- law-digest: everything below this line is generated by scripts/law-digest.py; do not edit by hand -->"

# Same heading grammar as prd-index-audit.py (unbounded number: §1000+ is real).
SECTION_HEADING = re.compile(r"^##\s+(?:§)?(\d+[a-z]{0,2})\b(.*)$")
SUB_ENTRY = re.compile(
    r"^\s*(?:(?:first|second|third|fourth|fifth|sixth|seventh|eighth|ninth|tenth)\s+)?"
    r"(amendment|follow-up)", re.I)
SUB_HEADING = re.compile(r"^#{3,6}\s+(§\d+[a-z]{0,2}|\d+[a-z]{1,2})\b")
REF = re.compile(r"§(\d+[a-z]{0,2})\b")

KILL = {"supersede", "supersedes", "superseded", "reverse", "reverses", "reversed",
        "overturn", "overturns", "overturned", "retire", "retires", "retired",
        "delete", "deletes", "deleted", "withdraw", "withdraws", "withdrawn",
        "replace", "replaces", "replaced", "declined", "ruled", "overtaken"}
AMEND = {"amend", "amends", "amended", "extend", "extends", "extended",
         "narrow", "narrows", "narrowed", "answered", "refines", "refined"}

# A qualifier that turns a kill into a clause-kill, wherever it sits in the
# phrase: "superseded in part by", "Frames half reversed by", "superseded by
# §941 in the Wallet", "amended … for ONE event", "as the SURFACE only".
PARTIAL_WORDS = re.compile(
    r"\b(in part|in shape|half|item \d|items?|clause|default|for the|for those|"
    r"for one|for polar|for walletbeat|for [A-Z]|in the wallet|only|as the)\b", re.I)

INDEX_START = "## Superseded index"
INDEX_END = "\n## 1. Thesis"

# Rulings the Superseded index records as dead WHOLE that the ledger itself
# says still stand. Each entry is a conscious "the row over-claims", with the
# reason, in the shape of prd-index-audit.py's KNOWN_DANGLING. The fix of
# record is the index row; until it is amended, the digest keeps the ruling
# live and marks it "part superseded" by the row's changers.
LIVE_DESPITE_INDEX = {
    "61": "the row reads 'superseded by §97, reversed by §114', but §97 replaced "
          "only item 4 (the empty-feed door) and §114 only the Markets placement; "
          "Known stale's own row says 'the ladder itself stands'",
}


# --------------------------------------------------------------------------
# Parsing
# --------------------------------------------------------------------------

def strip_trailing_paren(title):
    """Split "Title (user: "…", 2026-09-29; supersedes §X)" into the title and
    the trailing parenthetical. The trailing group is the one whose opening
    paren closes exactly at the end of the line; quotes inside it may hold
    balanced parens of their own, so the walk counts depth."""
    t = title.rstrip()
    if not t.endswith(")"):
        # A truncated or unbalanced heading: fall back to the first " (user"
        # / " (20xx-" / " (same canvas" opening.
        m = re.search(r"\s\((?:user|20\d\d-|same |the |ruling|amend|Option)", t)
        return (t[:m.start()].rstrip(), t[m.start():]) if m else (t, "")
    depth = 0
    for i in range(len(t) - 1, -1, -1):
        c = t[i]
        if c == ")":
            depth += 1
        elif c == "(":
            depth -= 1
            if depth == 0:
                return t[:i].rstrip(), t[i:]
    m = re.search(r"\s\((?:user|20\d\d-|same |the |ruling|amend|Option)", t)
    return (t[:m.start()].rstrip(), t[m.start():]) if m else (t, "")


def clean_title(rest):
    rest = rest.strip()
    rest = re.sub(r"^[\s.—–:-]+", "", rest)
    title, paren = strip_trailing_paren(rest)
    title = title.strip().rstrip(" —-–:")
    title = re.sub(r"\s+", " ", title)
    if len(title) > 120:
        title = title[:117].rstrip() + "…"
    return title, paren


def parse_sections(text):
    """[{num, line, title, paren, subs}] for every H2 section, in document
    order. Amendment/follow-up H2s and letter-suffixed H3s are counted on the
    section that owns them, not listed as rulings of their own."""
    sections, by_num, current = [], {}, None
    for i, line in enumerate(text.split("\n"), 1):
        m = SECTION_HEADING.match(line)
        if m:
            num, rest = m.group(1), m.group(2)
            if SUB_ENTRY.match(rest.lstrip(" .—-")):
                if num in by_num:
                    by_num[num]["subs"] += 1
                continue
            title, paren = clean_title(rest)
            s = {"num": num, "line": i, "title": title, "paren": paren, "subs": 0}
            sections.append(s)
            by_num[num] = s
            current = s
            continue
        if current is not None and SUB_HEADING.match(line):
            current["subs"] += 1
    # A bare "## §536" heading carries its title as the body's bold lead.
    lines = text.split("\n")
    for s in sections:
        if s["title"]:
            continue
        lead = " ".join(l.strip() for l in lines[s["line"]:s["line"] + 4]).strip()
        m = re.match(r"\*\*(.+?)(?:\*\*|$)", lead)
        if m:
            s["title"], _ = clean_title(m.group(1).rstrip("."))
    return sections, by_num


def split_top_level(cell):
    """Drop every parenthesized span (depth-aware) so a verb phrase about a
    DIFFERENT ruling, inside an explanation, is never read as this row's."""
    out, depth = [], 0
    for c in cell:
        if c == "(":
            depth += 1
            continue
        if c == ")":
            depth = max(0, depth - 1)
            continue
        if depth == 0:
            out.append(c)
    return "".join(out)


VERB_BY = re.compile(
    r"([\w'’ ]{0,30}?)\b(" + "|".join(sorted(KILL | AMEND, key=len, reverse=True)) +
    # The tail after the refs is a LOOKAHEAD: consuming it swallowed the next
    # verb, so "superseded by §97, reversed by §114" lost §114.
    r")\b([^§]{0,40}?)\bby\s+((?:§\d+[a-z]{0,2}(?:\s*(?:,|and|&)\s*)?)+)(?=([^,;—|]{0,40}))",
    re.I)


def _norm(x):
    return re.sub(r"[^a-z0-9 ]", "", x.lower().replace("—", " ")).split()


def title_matches(qual, title):
    """Does a row's description name the WHOLE ruling? Yes when it is the
    ruling's own title (a prefix either way, or most of its first words)."""
    q, t = _norm(qual), _norm(title)
    if not q or not t:
        return False
    qs, ts = " ".join(q), " ".join(t)
    # A PREFIX, never word overlap. "the box gives way" lies wholly inside
    # §772's title and "the tray's Manage is a room's one door" shares 7 of
    # 10 words with §937's — both are clauses, and both rulings stand. A
    # wrongly-kept clause costs a "part superseded" note; a wrongly-killed
    # ruling vanishes from the digest, so overlap never decides.
    return ts.startswith(qs[:20]) or qs.startswith(ts[:20])


def parse_targets(col1, by_num, what=""):
    """Col 1 of an index row → [(num, whole?)]. Whole only when the cell names
    the ruling bare, or names it by its own title."""
    out = []
    parts = re.split(r"\s+/\s+|\s+and\s+(?=§)", col1)
    for p in parts:
        p = p.strip().strip("*")
        refs = REF.findall(p)
        if not refs:
            continue
        # "§247 / §309 / §375 (the import rooms' …)" — the qualifier rides the
        # last part but describes them all, so a bare part is not "whole".
        m = re.match(r"^§(\d+[a-z]{0,2})\s*(?:\((.*)\))?\s*$", p)
        if m:
            num, qual = m.group(1), m.group(2)
            title = by_num[num]["title"] if num in by_num else ""
            if qual is None:
                # A bare number: whole only when "What it said" is the
                # ruling's own title — §500 has three bare rows, one per
                # clause, and none of them is the seat ruling's title.
                whole = len(parts) == 1 and title_matches(what, title)
            else:
                whole = title_matches(qual, title)
            out.append((num, whole))
        else:
            # "§548's tail order (…)", "§983 item 2 (…)", "§529 §4 (…)",
            # "§916 amendment (…)" — a clause.
            out.append((refs[0], False))
    return out


def parse_effects(col3):
    """Col 3 → [(kind, changer, partial)] read from TOP-LEVEL text only.
    kind is 'kill' or 'amend'. A kill is WHOLE only when its verb opens its
    clause ("superseded by §97", "amended by §36j, superseded by §36o"); a
    subject in front of the verb names the part that died ("default reversed
    by §393a", "the glass tray itself … deleted by §712", "Frames half
    reversed by §504")."""
    top = split_top_level(col3)
    effects = []
    # "…; §775 is in turn superseded by §904" is a fact about §775 riding this
    # row, not about the row's ruling — drop any clause whose subject is a §.
    own = ";".join(c for c in top.split(";")
                   if not re.match(r"\s*§\d+[a-z]{0,2}\s+(?:is|was|in turn|itself)\b", c))
    for m in VERB_BY.finditer(own):
        _, verb, between, refs, after = m.groups()
        verb = verb.lower()
        kind = "kill" if verb in KILL else "amend"
        head = own[:m.start(2)]
        cut = max(head.rfind(";"), head.rfind(","), head.rfind("—"), head.rfind(":"))
        subject = head[cut + 1:].strip().strip("*").strip()
        subject = re.sub(r"^(?:and then|and|then|later|since)\b", "", subject, flags=re.I).strip()
        partial = bool(subject
                       or PARTIAL_WORDS.search(between or "")
                       or re.match(r"\s*\**\s*(in the wallet|for |as the |only)", after or "", re.I))
        for r in REF.findall(refs):
            effects.append((kind, r, partial))
    if not effects:
        # Known-stale shape: "§100 — the tab bar was dropped …" (no verb).
        m = re.match(r"^\s*§(\d+[a-z]{0,2})\b", top)
        if m:
            effects.append(("kill", m.group(1), False))
    return effects


def index_rows(text):
    start = text.find(INDEX_START)
    if start < 0:
        return []
    end = text.find(INDEX_END, start)
    block = text[start:end if end > 0 else len(text)]
    rows = []
    for line in block.split("\n"):
        if not line.startswith("|") or re.match(r"^\|[\s|:-]+\|?$", line):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or cells[0] in ("Ruling", "Now"):
            continue
        rows.append((cells[0], cells[1], " | ".join(cells[2:])))
    return rows


HEAD_VERB = re.compile(
    r"\b(supersedes?|amends?|reverses?|overturns?|retires?|replaces?|extends?|"
    r"narrows?|withdraws?|deletes?)\b", re.I)
HEAD_PASSIVE = re.compile(
    r"\b(?:superseded|reversed|overturned|retired|withdrawn|replaced)\b[^;)§]{0,40}?\bby\s+§(\d+[a-z]{0,2})", re.I)
HEAD_REF = re.compile(r"(?:§)?(\d+[a-z]{0,2})\b(['’]s|\s+item\b|\s+for\b)?")


def header_effects(paren):
    """The heading's own parenthetical: "(…; supersedes §1008, amends §1011,
    §976a and §958)". Each verb owns the refs up to the next verb or ';'."""
    out = []
    if not paren:
        return out
    verbs = list(HEAD_VERB.finditer(paren))
    for k, vm in enumerate(verbs):
        stop = verbs[k + 1].start() if k + 1 < len(verbs) else len(paren)
        seg = paren[vm.end():stop]
        seg = re.split(r"[;)]", seg)[0]
        verb = vm.group(1).lower()
        kind = "amend" if verb.rstrip("s") in ("amend", "extend", "narrow") else "kill"
        # Only refs at the head of the segment, joined by , / and — so
        # "supersedes §729's commit row, follows §1027" stops at the clause.
        pos = 0
        seg_s = seg
        while True:
            mm = re.match(r"\s*(?:,|/|and|&)?\s*", seg_s[pos:])
            pos += mm.end()
            rm = HEAD_REF.match(seg_s, pos)
            if not rm or (not seg_s[pos:].startswith("§") and not re.match(r"\d+[a-z]{0,2}\b", seg_s[pos:])):
                break
            # A bare number must be a pre-§ section like "36a", never "2026".
            if not seg_s[pos:].startswith("§") and len(re.match(r"\d+", rm.group(1)).group(0)) > 3:
                break
            partial = bool(rm.group(2))
            out.append((kind, rm.group(1), partial))
            pos = rm.end()
            # Words after a ref and before the next separator make it a clause.
            tail = re.match(r"([^,/]*?)(?=\s*(?:,|/|\band\b|$))", seg_s[pos:])
            if tail and tail.group(1).strip():
                out[-1] = (kind, rm.group(1), True)
                pos += tail.end()
    return out


def compute(text, live_despite=None):
    """→ (sections, by_num, dead {num: [changers]}, notes {num: [(kind, by)]},
    renames {old: new})."""
    sections, by_num = parse_sections(text)
    dead, notes, renames = {}, {}, {}

    def note(num, kind, by):
        if num == by:
            return
        lst = notes.setdefault(num, [])
        if (kind, by) not in lst:
            lst.append((kind, by))

    for col1, col2, col3 in index_rows(text):
        # A pure renumber row: "| §236b | §236 | collided with … |".
        if re.fullmatch(r"§\d+[a-z]{0,2}", col1) and re.fullmatch(r"§\d+[a-z]{0,2}", col2):
            renames[col2[1:]] = col1[1:]
            continue
        targets = parse_targets(col1, by_num, col2)
        effects = parse_effects(col3)
        for num, whole in targets:
            for kind, by, partial in effects:
                if kind == "kill" and whole and not partial:
                    dead.setdefault(num, [])
                    if by not in dead[num]:
                        dead[num].append(by)
                elif kind == "kill":
                    note(num, "part superseded", by)
                else:
                    note(num, "amended", by)

    for s in sections:
        # PASSIVE, about the heading itself: "(recorded 2026-09-27; superseded
        # the next day by §969)" — the entry was written already dead.
        for pm in HEAD_PASSIVE.finditer(s["paren"]):
            dead.setdefault(s["num"], [])
            if pm.group(1) not in dead[s["num"]]:
                dead[s["num"]].append(pm.group(1))
        for kind, ref, partial in header_effects(s["paren"]):
            if ref == s["num"]:
                continue
            if kind == "kill" and not partial:
                dead.setdefault(ref, [])
                if s["num"] not in dead[ref]:
                    dead[ref].append(s["num"])
            elif kind == "kill":
                note(ref, "part superseded", s["num"])
            else:
                note(ref, "amended", s["num"])
    for num in (live_despite or {}):
        for by in dead.pop(num, []):
            note(num, "part superseded", by)
    return sections, by_num, dead, notes, renames


def sort_key(num):
    m = re.match(r"(\d+)([a-z]*)", num)
    return (int(m.group(1)), m.group(2))


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def chain_text(chain):
    part = sorted({b for k, b in chain if k == "part superseded"}, key=sort_key)
    amended = sorted({b for k, b in chain if k == "amended"} - set(part), key=sort_key)
    bits = []
    if amended:
        bits.append("amended by " + ", ".join("§" + b for b in amended))
    if part:
        bits.append("part superseded by " + ", ".join("§" + b for b in part))
    return f" ({'; '.join(bits)})" if bits else ""


def render(text, live_despite=None):
    sections, by_num, dead, notes, renames = compute(text, live_despite)
    live = [s for s in sections if s["num"] not in dead]
    lines = [MARKER, "",
             "## Live rulings, every one (generated)",
             "",
             f"{len(live)} of {len(sections)} H2 rulings in `docs/prd.md` are not superseded, "
             f"reversed, deleted or retired WHOLE by anything the ledger records "
             f"(the Superseded index, Known stale, Renumbered, and each heading's own "
             f"parenthetical). \"Part superseded\" means a CLAUSE of the ruling was "
             f"replaced — read the later entry before citing that clause. Numbers "
             f"1–33 are the original spec chapters. A ruling outgrown with no phrase "
             f"anywhere still reads as live here; the by-area section above is the "
             f"judgement layer.",
             ""]
    for s in sorted(live, key=lambda s: sort_key(s["num"])):
        sub = f" [+{s['subs']} sub-entries]" if s["subs"] else ""
        lines.append(f"- §{s['num']} — {s['title']}{chain_text(notes.get(s['num'], []))}{sub}")
    lines += ["", "## Dead rulings → what replaced them (generated)", "",
              "Superseded, reversed, deleted or retired whole. Read the right-hand "
              "entry instead; the left one is history.", ""]
    dead_known = sorted((n for n in dead if n in by_num), key=sort_key)
    lines.append(" · ".join(f"§{n}→{'/'.join('§' + b for b in sorted(dead[n], key=sort_key))}"
                            for n in dead_known))
    if renames:
        lines += ["", "## Renumbered (generated)", "",
                  " · ".join(f"§{old}→§{new}" for old, new in
                             sorted(renames.items(), key=lambda kv: sort_key(kv[0])))]
    lines.append("")
    return "\n".join(lines), {"total": len(sections), "live": len(live),
                              "dead": len(dead_known), "dead_set": set(dead_known),
                              "part": sum(1 for s in live if any(k == "part superseded" for k, _ in notes.get(s["num"], []))),
                              "amended": sum(1 for s in live if notes.get(s["num"]))}


DEFAULT_HEAD = """# Casberi — current law

(Hand-written section goes here. Everything below the marker is generated.)

"""


def hand_half_citations(hand):
    return set(REF.findall(hand))


def check_hand_half(hand, dead_set):
    """A rule in the by-area half that cites a ruling the ledger now records as
    dead is a stale rule. The 'Conflicts' and history lines may name dead
    rulings on purpose, so only lines that are rules (start with '- ') before
    the conflicts heading are checked."""
    bad = []
    body = hand.split("## Conflicts to resolve")[0]
    for ln in body.split("\n"):
        if not ln.lstrip().startswith("- "):
            continue
        for num in REF.findall(ln):
            if num in dead_set:
                bad.append((num, ln.strip()[:110]))
    return bad


# --------------------------------------------------------------------------
# Self-test: every case is a shape the real ledger holds.
# --------------------------------------------------------------------------

FIXTURE = """# PRD

## Superseded index

| Ruling | What it said | Changed by |
|---|---|---|
| §61 | The elevation ladder | superseded by §97, reversed by §114 |
| §772 (the box gives way) | a thin cover stops claiming the box | superseded by §904 (no cover shrinks) |
| §772 (a figure face always earns the box) | covers hold the box | amended by §775 (in All no cover holds it) |
| §760 | Every lead is leadHeight | amended by §775 (in All no cover holds it); §775 is in turn superseded by §904 (every cover holds the box) |
| §306 (quiet hours) / §770 (its switch) | held until morning | deleted by §870 (nobody understands it) |
| §500 | no notifications | amended by §522 for ONE event |
| §606 | a gas budget bar | superseded in part by §692 (the bar goes) |
| §940 (the Accounts crown is a bar) | bars | superseded by §941 in the Wallet — the crown is faces |
| §36a | Home cover | amended by §36j, superseded by §36o |
| §1001 (The tray's marks stay on the row size) | 28pt | superseded by §1008 — the user reopened it |
| §393 | Use what Apple uses | default reversed by §393a — the material is back; the glass tray itself, its flag and its tokens deleted by §712 |
| §57 | Telegram REMOVED from the catalog | reversed by §456 (a public channel is not a chat) |
| §937 (the tray's Manage is a room's one door) | a Manage circle in the You row | superseded by §958 — the You row is Home, Connect |

### Known stale, by hand

| Ruling | Still narrates | Actually in force |
|---|---|---|
| §16 (Shell) | a tab bar | §100 — the tab bar was dropped |
| §548's tail order ("frames leads") | the strip order | amended by §688 — Holdings leads |

### Renumbered entries

| Now | Was | Why it moved |
|---|---|---|
| §236b | §236 | collided with the connect-page ruling |
| §983 item 2 (the rest follow Pinned) | no header | amended by §985 — the rest stand under Notes |

## 1. Thesis

## 16. Shell

## 36a. Home cover: a banner outranks the screenshot (2026-07-09)

## 36j. Home cover is 2-tier (2026-07-10, amends 36a)

## 36o. The Banner is a BACKGROUND (2026-07-10, user — supersedes 36a/36j)

## §57 — Messages are social, not media (2026-07-11)

## §61 — The elevation ladder

## §97 — Doors

## §100 — One surface

## §114 — Undo the doors

## §236b — Connect pages

## §306 — Notifications (2026-08-05)

## §319 — The agent economy

## §319 amendment — the x402 room (user: "do all", 2026-08-10)

### 319a. A follow-up nested under it

## §393 — Use what Apple uses, and keep the recipe (user: "x", 2026-08-17)

## §500 — Hegotá (user: "no dots", 2026-08-27)

## §536

**Polar lands SALES (user ruling, 2026-08-31) — amending the doctrine.** Reported as

## §548 — The Frames room

## §606 — Privacy scopes

## §772 — The lead ladder, and the box gives way (user: "fill it (the box)", 2026-09-17)

## §760 — Every lead is leadHeight

## §770 — Notification categories

## §870 — Quiet hours go

## §937 — The room's corner door is deleted: the tray's Manage is the one door to a room's account page (user: "x", 2026-09-26)

## §940 — The accounts crown

## §941 — Faces

## §969 — Notes is a room (2026-09-29)

## §981 — A note edits (user: "edit", 2026-09-29; supersedes §969's "never opened for editing again")

## §983 — Notes, toward Apple

## §1001 — The tray's marks stay on the row size (user: "cohesive", 2026-09-29)

## §1008 — The tray's marks grow (user: "bigger", 2026-09-30; supersedes §1001)

## §1012 — Doors (user: "x", 2026-09-30; supersedes §1008, amends §1011, §976a and §958)

## §961 — Pinned as a fifth door in You (recorded from the tree, 2026-09-27; superseded the next day by §969)

## §1003 — Five seats retire (fixture: a number that resolves, so the index audit never reads it as a claim) (user: "retire them", 2026-10-01; retires §500 and §606)
"""


def self_test(verbose=True):
    ok = True

    def check(why, got):
        nonlocal ok
        if not got:
            ok = False
        if verbose or not got:
            print(f"  {'ok  ' if got else 'FAIL'} {why}")

    sections, by_num, dead, notes, renames = compute(FIXTURE)
    live = {s["num"] for s in sections if s["num"] not in dead}
    n = lambda num: notes.get(num, [])

    check("a bare index row kills the ruling (§61 superseded by §97)", "61" not in live)
    check("two verbs in one cell both land ('superseded by §97, reversed by §114')",
          set(dead.get("61", [])) == {"97", "114"})
    check("a row naming the ruling by its own title kills it (§1001)", "1001" not in live)
    check("a heading's 'supersedes §1001' kills it too, four digits", "1008" in dead.get("1001", []))
    check("a later supersede of the killer kills the killer (§1008 by §1012)", "1008" not in live)
    check("a clause-qualified row leaves the ruling live (§306 (quiet hours))",
          "306" in live and ("part superseded", "870") in n("306"))
    check("'superseded in part by' is a clause, not a death (§606 → §692)",
          ("part superseded", "692") in n("606"))
    check("'superseded by §941 in the Wallet' is a clause (§940 stays live)",
          "940" in live and ("part superseded", "941") in n("940"))
    check("'amended … for ONE event' is a chain link (§500 → §522)", ("amended", "522") in n("500"))
    check("a qualifier sharing most of the title's words is still a clause (§937 stands)",
          "937" in live and ("part superseded", "958") in n("937"))
    check("a subject before the verb is a clause ('default reversed by', 'the glass tray … deleted by')",
          "393" in live and {("part superseded", "393a"), ("part superseded", "712")} <= set(n("393")))
    check("a bare row whose 'What it said' is not the title is a clause (§57's Telegram half)",
          "57" in live and ("part superseded", "456") in n("57"))
    check("'…; §775 is in turn superseded by §904' is about §775, not this row's §760",
          "760" in live and all(b != "904" for _, b in n("760")) and ("amended", "775") in n("760"))
    check("a qualifier that merely shares the title's words is a clause ('the box gives way')",
          "772" in live and ("part superseded", "904") in n("772"))
    check("…and the row's own top-level verb still lands (§772 amended by §775)",
          ("amended", "775") in n("772"))
    check("Known stale, verbless ('§100 — …') kills a ruling named by its title (§16)",
          "16" not in live and dead.get("16") == ["100"])
    check("Known stale 'tail order' clause is an amendment chain link (§548 → §688)",
          "548" in live and any(b == "688" for _, b in n("548")))
    check("a pure renumber row is a rename, not a death (§236 → §236b)",
          renames.get("236") == "236b" and "236b" in live)
    check("a non-rename row in the Renumbered table is still read (§983 item 2 → §985)",
          "983" in live and any(b == "985" for _, b in n("983")))
    check("pre-§ heading spelling 'supersedes 36a/36j' kills both",
          "36a" not in live and "36j" not in live and "36o" in live)
    check("'amends 36a' in a heading is a chain link, not a death", ("amended", "36j") in n("36a"))
    check("a possessive clause in a heading ('§969's \"never opened…\"') leaves §969 live",
          "969" in live and ("part superseded", "981") in n("969"))
    check("one heading, two verbs: 'supersedes §1008, amends §1011, §976a and §958'",
          all(("amended", "1012") in n(x) for x in ("1011", "976a", "958")))
    check("'retires §500 and §606' kills both (the seat-retirement shape)",
          "500" not in live and "606" not in live)
    check("a heading that says it was itself 'superseded the next day by §969' is dead",
          "961" not in live and dead.get("961") == ["969"])
    check("an amendment H2 is counted on its parent, not listed as a ruling",
          sum(1 for s in sections if s["num"] == "319") == 1 and by_num["319"]["subs"] == 2)
    check("a heading's trailing user quote is stripped from its title",
          by_num["772"]["title"] == "The lead ladder, and the box gives way" and by_num["1001"]["title"] == "The tray's marks stay on the row size")
    kept = compute(FIXTURE, {"61": "test"})
    check("a LIVE_DESPITE_INDEX entry keeps an over-claimed ruling live, chain kept",
          "61" not in kept[2] and ("part superseded", "97") in kept[3].get("61", []))
    check("a bare '## §536' heading takes its body's bold lead as its title",
          by_num["536"]["title"] == "Polar lands SALES")
    out, stats = render(FIXTURE)
    check("the render lists a live ruling with its chain",
          "- §772 — The lead ladder, and the box gives way (amended by §775; part superseded by §904)" in out)
    check("the render never lists a dead ruling as live", "\n- §61 — " not in out)
    check("the dead list points a dead ruling at its replacement", "§1001→§1008" in out)
    bad = check_hand_half("## Design\n\n- The tray marks are 28pt (§1001).\n\n## Conflicts to resolve\n\n- §61 vs §114\n",
                          stats["dead_set"])
    check("--check flags a by-area rule citing a dead ruling, and not the Conflicts list",
          [b[0] for b in bad] == ["1001"])
    return ok


# --------------------------------------------------------------------------

def main(argv):
    if "--self-test" in argv:
        print("law-digest self-test")
        return 0 if self_test() else 1
    if not self_test(verbose=False):
        print("✗ law-digest: SELF-TEST FAILED — not writing a digest the parser cannot stand behind")
        return 1
    text = LEDGER.read_text(encoding="utf-8")
    generated, stats = render(text, LIVE_DESPITE_INDEX)
    existing = LAW.read_text(encoding="utf-8") if LAW.exists() else ""
    hand = existing.split(MARKER)[0] if MARKER in existing else (existing or DEFAULT_HEAD)
    hand = hand.rstrip("\n") + "\n\n"
    stale = check_hand_half(hand, stats["dead_set"])
    summary = (f"{stats['live']} live of {stats['total']} rulings · {stats['dead']} dead · "
               f"{stats['amended']} live with an amendment chain · {stats['part']} part superseded")
    if "--stats" in argv:
        print(summary)
        return 0
    new = hand + generated
    if "--check" in argv:
        problems = []
        if existing != new:
            problems.append("docs/law.md is stale — run `python3 scripts/law-digest.py`")
        for num, line in stale:
            problems.append(f"the by-area half cites §{num}, which the ledger records as dead: {line}")
        if problems:
            print("✗ law digest:")
            for p in problems:
                print(f"  {p}")
            return 1
        print(f"✓ law digest current: {summary}")
        return 0
    LAW.write_text(new, encoding="utf-8")
    print(f"wrote {LAW.relative_to(ROOT)} ({len(new.encode('utf-8')) // 1024} KB): {summary}")
    for num, line in stale:
        print(f"  ! by-area rule cites dead §{num}: {line}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
